### PR TITLE
fix(p2p): various reconnection issues

### LINKED ISSUE #719: Inbound peers block shutdown process
As identified in #699 by @offerm, we aren't closing pending inbound peer connections on shutdown. This can prevent `xud` from shutting down gracefully.

Edit: Per offer, it's not a pending connection that causes this issue but an established one. There must be something else coming into play because simply getting an inbound peer and shutting down doesn't reproduce the bug for me.

### LINKED ISSUE #721: [Overview] Reconnect to peer after disconnection (Improvements)
Improvement of https://github.com/ExchangeUnion/xud/pull/695:
* #738 - Reconnect after receiving AlreadyConnected disconnecting reason
* #739 - Reconnect only for outgoing peers. No need to reconnect incoming peers.
* Bug: A will not reconnect to B when B is down with xucli shutdown
* Bug: If A and B are connected (both can initiate the connection) and you take B down (kill), start B, wait a minute, Kill again ----> A will not attempt reconnect (reason is not cleared).
* Change max time between reconnections to 5 minutes (@offerm) vs. incremental increasing delay between retries (https://github.com/ExchangeUnion/xud/issues/311#issuecomment-413327480)
* Reset the counter only when we made a good connection.
* ~~The reconnection process will stop after 168 hours for some reason.~~
* ~~(duplicate) handle xucli shutdown (https://github.com/ExchangeUnion/xud/pull/695#issuecomment-443851789)~~

### LINKED ISSUE #738: Reconnect after receiving AlreadyConnected disconnecting reason
My node is up and running connected to test1,2,3.  My node does advertise listen address.
After some time, the node is not connected to the test servers any more.

Here is the log:

```
12/5/2018, 3:08:11 PM [ORDERBOOK] debug: order added: {"pairId":"LTC/BTC","price":0.9,"quantity":0.001,"isBuy":true,"hold":0,"id":"cf3f6bb0-f7ed-11e8-bdb3-d7798d8e6b1c","initialQuantity":0.001,"peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","createdAt":1544015291451}
12/5/2018, 3:08:11 PM [ORDERBOOK] debug: order added: {"pairId":"LTC/BTC","price":1.14,"quantity":0.003,"isBuy":false,"hold":0,"id":"cf3c8580-f7ed-11e8-bdb3-d7798d8e6b1c","initialQuantity":0.003,"peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","createdAt":1544015291452}
12/5/2018, 3:08:11 PM [ORDERBOOK] debug: order added: {"pairId":"LTC/BTC","price":1.1,"quantity":0.001,"isBuy":false,"hold":0,"id":"cf3fe0e0-f7ed-11e8-bdb3-d7798d8e6b1c","initialQuantity":0.001,"peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","createdAt":1544015291452}
12/5/2018, 3:08:11 PM [ORDERBOOK] debug: order added: {"pairId":"LTC/BTC","price":1.11,"quantity":0.0015,"isBuy":false,"hold":0,"id":"cf402f00-f7ed-11e8-bdb3-d7798d8e6b1c","initialQuantity":0.0015,"peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","createdAt":1544015291452}
12/5/2018, 3:08:11 PM [ORDERBOOK] debug: order added: {"pairId":"LTC/BTC","price":1.12,"quantity":0.002,"isBuy":false,"hold":0,"id":"cf407d20-f7ed-11e8-bdb3-d7798d8e6b1c","initialQuantity":0.002,"peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","createdAt":1544015291452}
12/5/2018, 3:08:11 PM [ORDERBOOK] debug: order added: {"pairId":"LTC/BTC","price":1.13,"quantity":0.0025,"isBuy":false,"hold":0,"id":"cf40cb40-f7ed-11e8-bdb3-d7798d8e6b1c","initialQuantity":0.0025,"peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","createdAt":1544015291452}
12/5/2018, 4:14:16 PM [P2P] debug: received disconnecting packet from 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a:{"reason":0,"payload":"05af92b0-f898-11e8-86f1-5f2201d5f5b5"}
12/5/2018, 4:14:16 PM [ORDERBOOK] debug: removed all orders for peer 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a
12/5/2018, 4:14:16 PM [P2P] info: Peer 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a socket closed
12/5/2018, 4:14:16 PM [P2P] debug: attempting to reconnect to a disconnected peer 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a
12/5/2018, 4:14:16 PM [P2P] debug: Connected pre-handshake to peer xud2.test.exchangeunion.com:8885
12/5/2018, 4:14:16 PM [P2P] verbose: received hello packet from xud2.test.exchangeunion.com:8885: {"version":"1.0.0-alpha.4","pairs":["LTC/BTC"],"nodePubKey":"028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a","lndbtcPubKey":"03d6747c9ff24aa8b025027e30556897543642910cbdec066d54f86841ab80966b","lndltcPubKey":"02ee4ff018591e42bd4a01dcc0e0a18c41f95640db2005d796492e08fb47b40bb5","addresses":[]}
12/5/2018, 4:14:16 PM [P2P] verbose: opened connection to 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a at xud2.test.exchangeunion.com:8885
12/5/2018, 4:14:16 PM [P2P] verbose: received 0 orders from 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a
12/5/2018, 4:14:16 PM [P2P] verbose: received 0 nodes (0 new) from 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a
12/5/2018, 5:06:00 PM [P2P] error: peer error (03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0): read ECONNRESET
12/5/2018, 5:06:00 PM [ORDERBOOK] debug: removed all orders for peer 03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0
12/5/2018, 5:06:00 PM [P2P] warn: Peer 03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0 socket closed due to error
12/5/2018, 5:06:00 PM [P2P] debug: attempting to reconnect to a disconnected peer 03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0
12/5/2018, 5:06:00 PM [P2P] debug: Connected pre-handshake to peer xud3.test.exchangeunion.com:8885
12/5/2018, 5:06:00 PM [P2P] verbose: received hello packet from xud3.test.exchangeunion.com:8885: {"version":"1.0.0-alpha.4","pairs":["LTC/BTC"],"nodePubKey":"03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0","lndbtcPubKey":"030c2ffd29a92e2dd2fb6fb046b0d9157e0eda8b11caa0e439d0dd6a46a444381c","lndltcPubKey":"02f5e0324909bdb635d4d6a50aa07c517db59f5d18219fd058f9faa3ef3a1fd83a","addresses":[]}
12/5/2018, 5:06:00 PM [P2P] verbose: opened connection to 03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0 at xud3.test.exchangeunion.com:8885
12/5/2018, 5:06:00 PM [P2P] debug: received disconnecting packet from 03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0:{"reason":7}
12/5/2018, 5:06:00 PM [ORDERBOOK] debug: removed all orders for peer 03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0
12/5/2018, 5:06:00 PM [P2P] info: Peer 03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0 socket closed
12/5/2018, 5:06:12 PM [P2P] error: peer error (02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6): read ECONNRESET
12/5/2018, 5:06:12 PM [ORDERBOOK] debug: removed all orders for peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6
12/5/2018, 5:06:12 PM [P2P] warn: Peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6 socket closed due to error
12/5/2018, 5:06:12 PM [P2P] debug: attempting to reconnect to a disconnected peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6
12/5/2018, 5:06:12 PM [P2P] debug: Connected pre-handshake to peer xud1.test.exchangeunion.com:8885
12/5/2018, 5:06:12 PM [P2P] verbose: received hello packet from xud1.test.exchangeunion.com:8885: {"version":"1.0.0-alpha.4","pairs":["LTC/BTC"],"nodePubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","lndbtcPubKey":"02d693d951ce4fc116b2b5e22e8e4966dd3cf9ad7600b8de24190d6af429f260c0","lndltcPubKey":"03114cda7206e92def08a35fc4039aba59394604fef9171ef19dbd5f938ce9387b","addresses":[]}
12/5/2018, 5:06:12 PM [P2P] verbose: opened connection to 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6 at xud1.test.exchangeunion.com:8885
12/5/2018, 5:06:12 PM [P2P] debug: received disconnecting packet from 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6:{"reason":7}
12/5/2018, 5:06:12 PM [ORDERBOOK] debug: removed all orders for peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6
12/5/2018, 5:06:12 PM [P2P] info: Peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6 socket closed
12/5/2018, 5:06:17 PM [P2P] error: peer error (028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a): read ECONNRESET
12/5/2018, 5:06:17 PM [ORDERBOOK] debug: removed all orders for peer 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a
12/5/2018, 5:06:17 PM [P2P] warn: Peer 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a socket closed due to error
12/5/2018, 5:06:17 PM [P2P] debug: attempting to reconnect to a disconnected peer 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a
12/5/2018, 5:06:17 PM [P2P] debug: Connected pre-handshake to peer xud2.test.exchangeunion.com:8885
12/5/2018, 5:06:17 PM [P2P] verbose: received hello packet from xud2.test.exchangeunion.com:8885: {"version":"1.0.0-alpha.4","pairs":["LTC/BTC"],"nodePubKey":"028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a","lndbtcPubKey":"03d6747c9ff24aa8b025027e30556897543642910cbdec066d54f86841ab80966b","lndltcPubKey":"02ee4ff018591e42bd4a01dcc0e0a18c41f95640db2005d796492e08fb47b40bb5","addresses":[]}
12/5/2018, 5:06:17 PM [P2P] debug: received disconnecting packet from 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a:{"reason":7}
12/5/2018, 5:06:17 PM [P2P] verbose: opened connection to 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a at xud2.test.exchangeunion.com:8885
12/5/2018, 5:06:17 PM [ORDERBOOK] debug: removed all orders for peer 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a
12/5/2018, 5:06:17 PM [P2P] info: Peer 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a socket closed
```

From what I see there was a  network problem, my node detected it and tried to reconnect. It got `already connected` from the test nodes since the test nodes didn't detect yet the problem.
After `already connected` there is no retry.

### LINKED ISSUE #739: Reconnect only for outgoing peers
Seen this on test2 server:

```
12/6/2018, 3:19:45 PM [P2P] error: peer error (03d2a862f7198143e96a08797e79c2ad86a09ee7a98494860cb1b9d73732c7e5bb): Peer (03d2a862f7198143e96a08797e79c2ad86a09ee7a98494860cb1b9d73732c7
e5bb) is stalling (56169410-f96a-11e8-ac3d-4f02ea5221a6)
12/6/2018, 3:19:45 PM [ORDERBOOK] debug: removed all orders for peer 03d2a862f7198143e96a08797e79c2ad86a09ee7a98494860cb1b9d73732c7e5bb
12/6/2018, 3:19:45 PM [P2P] debug: closing socket with peer 03d2a862f7198143e96a08797e79c2ad86a09ee7a98494860cb1b9d73732c7e5bb. reason: ResponseStalling
12/6/2018, 3:19:45 PM [P2P] debug: attempting to reconnect to a disconnected peer 03d2a862f7198143e96a08797e79c2ad86a09ee7a98494860cb1b9d73732c7e5bb
12/6/2018, 3:19:45 PM [P2P] warn: could not open connection to peer (03d2a862f7198143e96a08797e79c2ad86a09ee7a98494860cb1b9d73732c7e5bb): could not connect to peer at 127.0.0.1:9885: c
onnect ECONNREFUSED 127.0.0.1:9885
12/6/2018, 3:19:45 PM [P2P] info: Peer 03d2a862f7198143e96a08797e79c2ad86a09ee7a98494860cb1b9d73732c7e5bb socket closed
12/6/2018, 3:19:45 PM [P2P] debug: Connection attempt #1 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 5 sec...
12/6/2018, 3:19:50 PM [P2P] debug: Connection attempt #2 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 10 sec...
12/6/2018, 3:20:00 PM [P2P] debug: Connection attempt #3 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 20 sec...
12/6/2018, 3:20:20 PM [P2P] debug: Connection attempt #4 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 40 sec...
12/6/2018, 3:21:00 PM [P2P] debug: Connection attempt #5 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 80 sec...
12/6/2018, 3:22:20 PM [P2P] debug: Connection attempt #6 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 160 sec...
12/6/2018, 3:25:00 PM [P2P] debug: Connection attempt #7 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 320 sec...
12/6/2018, 3:30:20 PM [P2P] debug: Connection attempt #8 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 640 sec...
12/6/2018, 3:41:00 PM [P2P] debug: Connection attempt #9 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 1280 sec...
12/6/2018, 4:02:21 PM [P2P] debug: Connection attempt #10 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 2560 sec...
12/6/2018, 4:45:01 PM [P2P] debug: Connection attempt #11 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 3600 sec...
12/6/2018, 5:45:01 PM [P2P] debug: Connection attempt #12 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 3600 sec...
12/6/2018, 6:45:01 PM [P2P] debug: Connection attempt #13 to peer (127.0.0.1:9885) failed: connect ECONNREFUSED 127.0.0.1:9885. retrying in 3600 sec...
```

We should eliminate such reconnection.

### PR DESCRIPTION
**Pull request by ghost**
In this PR we add a series of improvements to the reconnection logic:
- only reconnect for outgoing peers
- reconnect after receiving `AlreadyConnected` disconnecting reason
- reconnect after receiving `Shutdown` disconnecting reason
- change max time between reconnections to 5 minutes
- fix the shutdown logic so that we correctly close pending connections and peers **before** closing the server

closes https://github.com/ExchangeUnion/xud/issues/721
closes https://github.com/ExchangeUnion/xud/issues/739
closes https://github.com/ExchangeUnion/xud/issues/738
closes https://github.com/ExchangeUnion/xud/issues/719

### CODE REVIEW

File: lib/p2p/Pool.ts [hunk 1]
```diff
@@ -185,14 +185,14 @@ class Pool extends EventEmitter {
       return;
     }
 
-    // ensure we stop listening for new peers before disconnecting from peers
+    // ensure we disconnect from existing peers before closing the server
```
Comment (erkarl) [inline lib/p2p/Pool.ts]: This change is required because otherwise the [server.close](https://nodejs.org/api/net.html#net_server_close_callback) triggered by `this.unlisten` never completed and resulted in an incomplete shutdown.

File: lib/p2p/Pool.ts [hunk 2]
```diff
@@ -750,36 +750,33 @@ class Pool extends EventEmitter {
...
+    }
   }
 
   private closePendingConnections = async () => {
     for (const peer of this.pendingOutboundPeers.values()) {
       await peer.close();
     }
-    this.pendingInboundPeers.forEach(peer => peer.close());
+    for (const peer of this.pendingInboundPeers) {
+      await peer.close();
```
Comment (sangaman) [inline lib/p2p/Pool.ts]: I'm thinking that a minor improvement for this and the `closePeers` method is to await all these promises in parallel. We should be trying to close all these connections at once I believe, not one at a time. Can be a different PR if you'd prefer but I figured that while we're changing these methods it might make sense.

**Review by sangaman — COMMENTED** [review]
Thanks for tackling these lingering and hard to pin down issues.

File: lib/p2p/Peer.ts [hunk 3]
```diff
@@ -90,7 +90,7 @@ class Peer extends EventEmitter {
   /** Connection retries min delay. */
   private static readonly CONNECTION_RETRIES_MIN_DELAY = 5000;
   /** Connection retries max delay. */
-  private static readonly CONNECTION_RETRIES_MAX_DELAY = 3600000;
+  private static readonly CONNECTION_RETRIES_MAX_DELAY = 300000;
```
[the remark this answers is not in the document]
Comment (sangaman) [reply lib/p2p/Peer.ts]: I actually meant to delete this comment, I saw that this change was intentional per the PR description.

File: lib/p2p/Pool.ts [hunk 4]
```diff
@@ -750,36 +750,33 @@ class Pool extends EventEmitter {
...
     peer.active = false;
 
-    // if handshake passed and peer disconnected from us for stalling or without specifying any reason -
-    // reconnect, for that might have been due to a temporary loss in connectivity
-    const unintentionalDisconnect =
+    const shouldReconnect =
       (peer.sentDisconnectionReason === undefined || peer.sentDisconnectionReason === DisconnectionReason.ResponseStalling) &&
-      (peer.recvDisconnectionReason === undefined || peer.recvDisconnectionReason === DisconnectionReason.ResponseStalling);
+      (peer.recvDisconnectionReason === undefined || peer.recvDisconnectionReason === DisconnectionReason.ResponseStalling ||
+       peer.recvDisconnectionReason === DisconnectionReason.AlreadyConnected ||
```
[the remark this answers is not in the document]
Comment (erkarl) [reply lib/p2p/Pool.ts]: This was added as a result of discussion in: https://github.com/ExchangeUnion/xud/issues/738

It does sound weird that we reconnect upon `AlreadyConnected`, but I didn't experience a connect/disconnect loop while doing it.

File: lib/p2p/Pool.ts (hunk 2 above)
Comment (erkarl) [reply lib/p2p/Pool.ts]: You're right, executing them in parallel makes sense. Changed `closePendingConnections`, and also `closePeers`.

File: lib/p2p/Pool.ts (hunk 1 above)
Comment (erkarl) [reply lib/p2p/Pool.ts]: Wouldn't the code above still result in a race condition between closing connections/peers and closing the server itself? I think it would still result in occasional incomplete shutdowns.

Comment (erkarl) [reply lib/p2p/Pool.ts]: I agree that it would be possible that we get a new connection after we've closed peers and pending connections, but before we stop listening. 

Ideally we'd have something like:
```
await server.pause()
await server.closeConnectionsAndPeers()
await server.close()
```

**Comment by kilrau** [comment]
Can we also test https://github.com/ExchangeUnion/xud/issues/719 against this branch?

File: lib/p2p/Pool.ts (hunk 1 above)
Comment (erkarl) [reply lib/p2p/Pool.ts]: @sangaman after reading the documentation of the [close event](https://nodejs.org/api/net.html#net_event_close) it looks like it'll always wait for the connections to be closed before emitting it. If I understand it correctly there's a guarantee that there won't be a race condition that I mentioned above.

That's a very elegant solution, thank you. :).

**Comment by erkarl** [comment]
@kilrau With this branch I wasn't able to reproduce bug described in #719 (tested with both inbound and outbound peers).

**Comment by kilrau** [comment]
Nice!

File: lib/p2p/Pool.ts (hunk 1 above)
Comment (sangaman) [reply lib/p2p/Pool.ts]: Yeah so as I understand the callback for the `close()` method is simply listening for the `close` event, which is emitted when the server closes AND all connections are ended. The `close()` method stops accepting new connections, but doesn't close existing connections.

So to run through my thinking again we:

1) Call `close` up front, which stops accepting new connections ASAP.
2) Begin closing all existing sockets in parallel.
3) Wait for all sockets to close, and for the `close` event which should be emitted once both the server and all existing sockets are closed.

**Review by sangaman — APPROVED** [review]
Looks great.
