### PR TITLE
fix(swaps): go to recovery for all failures

### LINKED ISSUE #1606: SwapRecovery v2
https://github.com/ExchangeUnion/xud/tree/fix/swap-recovery still has an issue where an unclaimed payment (taker) is not entering the swap recovery path.

### PR DESCRIPTION
**Pull request by sangaman**
This fixes a bug where failed swaps in the `SendingPayment` phase as maker would only be tracked by the `SwapRecovery` module if they failed due to a timeout error.

Closes #1606.

This bug was due to an oversight in the changes from #1600.

### CODE REVIEW

**Comment by kilrau** [comment]
Looks like travis failed due to an alias collission!? Restarted.

`2020-06-09 07:04:41.4141 [P2P][1] error: Unexpected error connecting to known peers on startup: 2.26 - alias MeadowOven refers to more than one node`

File: lib/swaps/Swaps.ts [hunk 1]
```diff
@@ -1147,11 +1139,19 @@ class Swaps extends EventEmitter {
...
-      // if we are the maker and we have accepted a swap deal but we haven't yet started paying the taker
-      // then we should cancel
-      const swapClient = this.swapClientManager.get(deal.role === SwapRole.Maker ? deal.makerCurrency : deal.takerCurrency)!;
-      swapClient.removeInvoice(deal.rHash).catch(this.logger.error); // we don't need to await the remove invoice call
+    if (deal.role === SwapRole.Maker) {
+      if (deal.phase === SwapPhase.SwapAccepted) {
+        // if we are the maker and we have accepted a swap deal but we haven't yet started paying the taker
+        // then we should cancel the invoice for our incoming payment if one exists
+        const swapClient = this.swapClientManager.get(deal.makerCurrency)!;
+        swapClient.removeInvoice(deal.rHash).catch(this.logger.error); // we don't need to await the remove invoice call
```
Comment (erkarl) [inline lib/swaps/Swaps.ts:1147]: Why not do the `removeInvoice` in `SwapRecovery`?

**Comment by sangaman** [comment]
> Looks like travis failed due to an alias collission!? Restarted.
> 
> `2020-06-09 07:04:41.4141 [P2P][1] error: Unexpected error connecting to known peers on startup: 2.26 - alias MeadowOven refers to more than one node`

Wow... that should be extremely unlikely for a tiny network of nodes like the one the sim tests spin up.

File: lib/lndclient/LndClient.ts [hunk 2]
```diff
@@ -631,8 +631,7 @@ class LndClient extends SwapClient {
     if (!this.isConnected()) {
       throw swapErrors.FINAL_PAYMENT_ERROR(errors.UNAVAILABLE(this.currency, this.status).message);
     }
-
-    this.logger.trace(`sending payment with ${JSON.stringify(request.toObject())}`);
+    this.logger.debug(`sending payment of ${request.getAmt()} with hash ${request.getPaymentHashString} to ${request.getDestString()}`);
```
Comment (erkarl) [inline lib/lndclient/LndClient.ts:634]: Should `getPaymentHashString` be a function call here?

File: lib/swaps/Swaps.ts (hunk 1 above)
Comment (sangaman) [reply lib/swaps/Swaps.ts:1147]: Hm we could, my thinking though is that if we haven't started sending payment yet and are just in the acceptance phase, there are no funds that can possibly be lost and no uncertainty as to whether it's safe to cancel invoices.

File: lib/lndclient/LndClient.ts (hunk 2 above)
Comment (sangaman) [reply lib/lndclient/LndClient.ts:634]: Yes absolutely, thanks for catching this.
