### PR TITLE
fix(p2p): allow connections with alias conflict 

### LINKED ISSUE #1687: Alias collision blocking xud to connect to known peers at startup
### How it is

alias collision is causing xud to stop trying to connect to know peers on startup and delay to a much later point in time
```
25/06/2020 10:00:49.168 [LND-BTC] info: trying to verify connection to lnd at lndbtc:10009
25/06/2020 10:00:49.432 [LND-BTC] warn: lnd is out of sync with chain, retrying in 5000 ms
25/06/2020 10:00:54.433 [LND-BTC] info: trying to verify connection to lnd at lndbtc:10009
25/06/2020 10:00:54.687 [LND-BTC] warn: lnd is out of sync with chain, retrying in 5000 ms
25/06/2020 10:00:57.536 [RPC] debug: received call /xudrpc.XudInit/UnlockNode
25/06/2020 10:00:57.547 [GLOBAL] info: Local nodePubKey is 025443023c0303eb5671522cda0d49acb0e74c77f1371bf86262bad637835eb9e4
25/06/2020 10:00:57.720 [CONNEXT] info: new status: Initialized
25/06/2020 10:00:57.723 [CONNEXT] info: trying to verify connection to connext
25/06/2020 10:00:58.031 [CONNEXT] info: new status: ConnectionVerified
25/06/2020 10:00:58.032 [P2P] info: Connecting to simnet XU network
25/06/2020 10:00:58.034 [P2P] info: p2p server listening on 0.0.0.0:28885
25/06/2020 10:00:58.038 [P2P] debug: Verifying reachability of advertised address: xe4vwapndzzxlz47fb3n7ysqq4wynqic4cceel3pv3s6ehr6j2t663qd.onion:28885
25/06/2020 10:00:58.056 [HTTP] info: http server listening on 0.0.0.0:28887
25/06/2020 10:00:58.814 [P2P] error: Unexpected error connecting to known peers on startup: 2.26 - alias TypeWheat refers to more than one node
25/06/2020 10:00:59.846 [LND-BTC] info: trying to verify connection to lnd at lndbtc:10009
25/06/2020 10:01:00.058 [RPC] debug: received call /xudrpc.Xud/GetBalance
25/06/2020 10:01:00.311 [LND-BTC] warn: lnd is out of sync with chain, retrying in 5000 ms
25/06/2020 10:01:00.854 [P2P] debug: Connected pre-handshake to 127.0.0.1:42382
25/06/2020 10:01:01.290 [P2P] debug: Peer 025443023c0303eb5671522cda0d49acb0e74c77f1371bf86262bad637835eb9e4 (LaundryBrush): closing socket. reason: ConnectedToSelf
25/06/2020 10:01:01.318 [P2P] warn: could not open connection to inbound peer (025443023c0303eb5671522cda0d49acb0e74c77f1371bf86262bad637835eb9e4 (LaundryBrush)): cannot attempt connection to self
25/06/2020 10:01:01.328 [P2P] info: Peer 025443023c0303eb5671522cda0d49acb0e74c77f1371bf86262bad637835eb9e4 (LaundryBrush) socket closed
25/06/2020 10:01:01.597 [P2P] verbose: Verified reachability of advertised address: xe4vwapndzzxlz47fb3n7ysqq4wynqic4cceel3pv3s6ehr6j2t663qd.onion:28885
25/06/2020 10:01:02.781 [RPC] debug: received call /xudrpc.Xud/ListOrders
25/06/2020 10:01:05.350 [LND-BTC] info: trying to verify connection to lnd at lndbtc:10009
25/06/2020 10:01:05.878 [LND-BTC] warn: lnd is out of sync with chain, retrying in 5000 ms
25/06/2020 10:01:06.519 [RPC] debug: received call /xudrpc.Xud/ListOrders
25/06/2020 10:01:09.011 [RPC] debug: received call /xudrpc.Xud/ListPeers
25/06/2020 10:01:10.007 [RPC] debug: received call /xudrpc.Xud/ListOrders
25/06/2020 10:01:10.155 [RPC] debug: received call /xudrpc.Xud/GetBalance
```

### How it should be

xud notes the collision, but still connects to other known peers on startup

### PR DESCRIPTION
**Pull request by sangaman**
This ensures that we don't prevent ourselves from connecting to nodes that have alias conflicts with other known nodes. Instead, we only throw errors when we try to use a conflicted alias for rpc calls, since we cannot resolve the alias to a unique node.

Fixes #1687.

### CODE REVIEW

File: lib/p2p/NodeList.ts [hunk 1]
```diff
@@ -233,13 +244,14 @@ class NodeList extends EventEmitter {
     const { nodePubKey } = node;
     const alias = pubKeyToAlias(nodePubKey);
     if (this.aliasToPubKeyMap.has(alias)) {
-      throw errors.ALIAS_CONFLICT(alias);
+      this.aliasToPubKeyMap.set(alias, 'CONFLICT');
```
Comment (hatmer) [inline lib/p2p/NodeList.ts:247]: I'm assuming that you are doing this for a good reason but if possible there should just be an error thrown when the conflict is discovered

Comment (sangaman) [reply lib/p2p/NodeList.ts:265]: Originally there was an error thrown here but that's one thing this PR is trying to change. We don't want to prevent ourselves from connecting to a node just because it has an alias conflict with another node. We will throw errors if we try to use a conflicted alias for RPC calls, however.

**Comment by sangaman** [comment]
> Maybe we shouldn't attempt to do write operations such as `ban/openchannel` etc. by referencing the alias?

We won't allow it when there's an alias conflict, but it'll still be allowed when we specify an alias that only refers to one node.

**Comment by sangaman** [comment]
I'm going to split the commit between the alias changes and moving the ban/unban test cases to jest and then merge.
