### PR TITLE
fix: grpc throws error for addpair/withdraw for wrong argument (#1844)

### LINKED ISSUE #1844: Syntax err in `walletwithdraw` response
### Actual behaviour

```
simnet > walletwithdraw
xucli walletwithdraw [amount] [currency] [destination] [fee]

withdraws on-chain funds from xud

Options:
  --help             Show help                                         [boolean]
  --version          Show version number                               [boolean]
  --rpcport, -p      RPC service port                                   [number]
  --rpchost, -h      RPC service hostname                               [string]
  --tlscertpath, -c  Path to the TLS certificate of xud                 [string]
  --json, -j         Display output in json format    [boolean] [default: false]
  --xudir, -x        Data directory for xud                             [string]
  --amount           the amount to withdraw                             [number]
  --currency         the ticker symbol of the currency to withdraw.     [string]
  --destination      the address to send withdrawn funds to             [string]
  --fee              the fee in satoshis (or equivalent) per byte       [number]
  --all              whether to withdraw all available funds           [boolean]

Examples:
  xucli withdraw 0.1 BTC                    withdraws 0.1 BTC
  1BitcoinEaterAddressDontSendf59kuE
  xucli withdraw 0.1 BTC                    withdraws 0.1 BTC using 20 sats/byte
  1BitcoinEaterAddressDontSendf59kuE 20
  xucli withdraw --all --currency BTC       withdraws all BTC
  --address
  1BitcoinEaterAddressDontSendf59kuE

TypeError: Cannot read property 'toUpperCase' of undefined
    at /app/dist/cli/commands/walletwithdraw.js:44:39
    at Generator.next (<anonymous>)
    at /app/dist/cli/commands/walletwithdraw.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/dist/cli/commands/walletwithdraw.js:4:12)
    at Object.exports.handler (/app/dist/cli/commands/walletwithdraw.js:42:29)
    at Object.runCommand (/app/node_modules/yargs/lib/command.js:237:40)
    at Object.parseArgs [as _parseArgs] (/app/node_modules/yargs/yargs.js:1090:30)
    at Object.get [as argv] (/app/node_modules/yargs/yargs.js:1024:21)
    at Object.<anonymous> (/app/bin/xucli:43:3)
```
Expected result:
No the syntax err

### PR DESCRIPTION
**Pull request by rsercano**
resolves #1844

Replaces #1846.

### CODE REVIEW

**Review by raladev — DISMISSED** [review]

File: lib/cli/commands/walletwithdraw.ts [hunk 1]
```diff
@@ -3,16 +3,16 @@ import { WithdrawRequest } from '../../proto/xudrpc_pb';
...
-    type: 'number',
+  .positional('amount', {
+    description: 'the amount to withdraw, `all` withdraws everything',
+    type: 'string',
   })
-  .option('currency', {
+  .positional('currency', {
     description: 'the ticker symbol of the currency to withdraw.',
     type: 'string',
   })
```
Comment (sangaman) [inline lib/cli/commands/walletwithdraw.ts:18]: I noticed one more thing here on another pass, the line below with `option('destination'` should be `positional('destination'`. Sorry if that's a headache with the commits, but you should be able to make the change and just do:

```
git add -A
git commit --amend --no-edit
git push --force
```

And it should update this PR with just that one line below.

**Review by sangaman — CHANGES_REQUESTED** [review]

File: lib/cli/commands/walletwithdraw.ts (hunk 1 above)
Comment (rsercano) [reply lib/cli/commands/walletwithdraw.ts:18]: I guess it worked, thanks a ton @sangaman :)

**Review by raladev — APPROVED** [review]

**Review by sangaman — APPROVED** [review]
