### PR TITLE
Order match swap execution fixes

### LINKED ISSUE #348: LN SWAP
No more words needed. Should be your sole focus for `alpha.1` (aka `Berlin` release) @sangaman 

image

### PR DESCRIPTION
**Pull request by sangaman**
Edit: Closes #348

This fixes a bug to properly set the amounts and taker lnd pub key for swaps triggered by order book matches.

To perform this yourself, first setup lnd according to the instructions in #348. Once you have btcd, ltcd, and 2 running lnd instances for each, run two instances of xud listening for rpc requests on the same ports as specified in the `resolver.conf` files.

Connect the nodes to each other, then place matching orders (I'm using the default 8886 rpc port for exchange a, and 9886 for exchange b)

```bash
xucli limitorder LTC/BTC 1 .1 .01
{
  "matchesList": [],
  "remainingOrder": {
    "price": 0.01,
    "quantity": 0.1,
    "pairId": "LTC/BTC",
    "peerPubKey": "",
    "id": "ea55dc70-a86c-11e8-81de-35e735f1f1ab",
    "localId": "1",
    "createdAt": 1535204637623,
    "invoice": "",
    "canceled": false
  }
}

xucli marketorder LTC/BTC 2 -1 -p 9886
{
  "matchesList": [
    {
      "maker": {
        "price": 0.01,
        "quantity": 0,
        "pairId": "LTC/BTC",
        "peerPubKey": "029a96c975d301c1c8787fcb4647b5be65a3b8d8a70153ff72e3eac73759e5e345",
        "id": "ea55dc70-a86c-11e8-81de-35e735f1f1ab",
        "localId": "",
        "createdAt": 1535204637631,
        "invoice": "",
        "canceled": false
      },
      "taker": {
        "price": 0,
        "quantity": -0.1,
        "pairId": "LTC/BTC",
        "peerPubKey": "",
        "id": "ee06d680-a86c-11e8-839d-5747ad4f1ba9",
        "localId": "3",
        "createdAt": 1535204643816,
        "invoice": "",
        "canceled": false
      }
    }
  ]
}
```

This will trigger the swap, you'll be able to see the results from the xud log output and the new `listchannels` lnd output.

### CODE REVIEW

File: lib/orderbook/MatchesProcessor.ts [hunk 1]
```diff
@@ -39,33 +39,35 @@ class MatchesProcessor {
...
+        takerAmount = taker.quantity * 100000000;
+        makerAmount = taker.quantity * maker.price * 100000000;
       } else {
         // we are selling the base currency
         takerCurrency = quoteCurrency;
         makerCurrency = baseCurrency;
-        takerAmount = taker.quantity * maker.price;
-        makerAmount = taker.quantity;
+        takerAmount = taker.quantity * maker.price * -100000000;
+        makerAmount = taker.quantity * -100000000;
```
Comment (offerm) [inline lib/orderbook/MatchesProcessor.ts]: Not sure why there is a need for negative numbers.

File: lib/orderbook/MatchesProcessor.ts [hunk 2]
```diff
@@ -39,33 +39,35 @@ class MatchesProcessor {
...
       let takerAmount: number;
       let makerAmount: number;
+       // TODO: use configurable amount of subunits/satoshis per token for each currency
       if (taker.quantity > 0) {
         // we are buying the base currency
         takerCurrency = baseCurrency;
         makerCurrency = quoteCurrency;
-        takerAmount = taker.quantity;
-        makerAmount = taker.quantity * maker.price;
+        takerAmount = taker.quantity * 100000000;
```
Comment (offerm) [inline lib/orderbook/MatchesProcessor.ts]: Not sure why multiple by 100000000 here and not working with these amounts in the command line itself

Comment (sangaman) [reply lib/orderbook/MatchesProcessor.ts]: The command line & rpc for placing orders uses whole tokens, whereas LND is expecting amounts in satoshis. This is just the number to convert bitcoin to satoshis.

File: lib/orderbook/MatchesProcessor.ts (hunk 1 above)
Comment (sangaman) [reply lib/orderbook/MatchesProcessor.ts]: Because `taker.quantity` is negative in this `else` block, the `if` statement above checks `if (taker.quantity > 0)`. This indicates that the taker order (aka the local order) is a sell order. Multiplying by a negative number brings it back to positive.
