### PR TITLE
fix(rpc): close listeners for streaming calls

### LINKED ISSUE #1640: SubscribeSwaps leaks memory
Looks like `SubscribeSwaps` stream listeners are not cleaned up properly:
```
11/06/2020 18:35:53.144 [RPC] debug: received call /xudrpc.Xud/GetBalance
11/06/2020 18:35:53.145 [RPC] debug: received call /xudrpc.Xud/TradingLimits
11/06/2020 18:35:58.168 [RPC] debug: received call /xudrpc.Xud/SubscribeSwaps
11/06/2020 18:35:58.171 [RPC] debug: received call /xudrpc.Xud/GetBalance
11/06/2020 18:35:58.173 [RPC] debug: received call /xudrpc.Xud/TradingLimits
11/06/2020 18:36:03.197 [RPC] debug: received call /xudrpc.Xud/SubscribeSwaps
(node:265240) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 swap.paid listeners added to [Swaps]. Use emitter.setMaxListeners() to increase limit
11/06/2020 18:36:03.204 [RPC] debug: received call /xudrpc.Xud/GetBalance
11/06/2020 18:36:03.207 [RPC] debug: received call /xudrpc.Xud/TradingLimits
11/06/2020 18:36:07.642 [RPC] debug: received call /xudrpc.Xud/AddCurrency
11/06/2020 18:36:08.239 [RPC] debug: received call /xudrpc.Xud/SubscribeSwaps
11/06/2020 18:36:08.242 [RPC] debug: received call /xudrpc.Xud/GetBalance
11/06/2020 18:36:08.244 [RPC] debug: received call /xudrpc.Xud/TradingLimits
11/06/2020 18:36:13.267 [RPC] debug: received call /xudrpc.Xud/SubscribeSwaps
11/06/2020 18:36:13.270 [RPC] debug: received call /xudrpc.Xud/GetBalance
```

### PR DESCRIPTION
**Pull request by sangaman**
This removes internal listeners that are created to handle streaming rpc calls. When the rpc call is canceled, we remove all listeners related to that call.

Fixes #1640.

### CODE REVIEW

File: lib/service/Service.ts [hunk 1]
```diff
@@ -678,38 +682,64 @@ class Service {
       });
     }
 
-    this.orderBook.on('peerOrder.incoming', order => callback(order));
-    this.orderBook.on('ownOrder.added', order => callback(order));
+    this.orderBook.on('peerOrder.incoming', callback);
+    this.orderBook.on('ownOrder.added', callback);
+
+    const removalCallback = (orderRemoval: OrderPortion) => callback(undefined, orderRemoval);
+    this.orderBook.on('peerOrder.invalidation', removalCallback);
```
Comment (erkarl) [inline lib/service/Service.ts:689]: These can also be merged together into 1 event since the callback is the same.

```
const orderRemoved$ = merge(
...
).pipe(
  takeUntil(cancelled$),
);
```

File: lib/service/Service.ts [hunk 2]
```diff
@@ -678,38 +682,64 @@ class Service {
...
+    this.orderBook.on('peerOrder.filled', removalCallback);
+    this.orderBook.on('ownOrder.filled', removalCallback);
+    this.orderBook.on('ownOrder.removed', removalCallback);
 
-    this.orderBook.on('peerOrder.invalidation', orderRemoval => callback(undefined, orderRemoval));
-    this.orderBook.on('peerOrder.filled', orderRemoval => callback(undefined, orderRemoval));
-    this.orderBook.on('ownOrder.filled', orderRemoval => callback(undefined, orderRemoval));
-    this.orderBook.on('ownOrder.removed', orderRemoval => callback(undefined, orderRemoval));
+    // we wait for the streaming call to be canceled
+    cancelledPromise.then(() => {
```
Comment (erkarl) [inline lib/service/Service.ts:695]: This cleanup won't be required because it will be handled by `takeUntil(cancelled$)`.

File: lib/service/Service.ts [hunk 3]
```diff
@@ -678,38 +682,64 @@ class Service {
...
+    cancelledPromise: Promise<void>,
+  ) => {
+    const onSwapPaid = (swapSuccess: SwapSuccess) => {
       // always alert client for maker matches, taker matches only when specified
       if (swapSuccess.role === SwapRole.Maker || args.includeTaker) {
         callback(swapSuccess);
       }
-    });
+    };
+    this.swaps.on('swap.paid', onSwapPaid);
```
Comment (erkarl) [inline lib/service/Service.ts:720]:
```
const swapPaid$ = from(this.swaps, 'swap.paid').pipe(
  takeUntil(cancelled$),
);

swapPaid$.subscribe({
  next: onSwapPaid,
  error: this.logger.error,
});
```

File: lib/service/Service.ts [hunk 4]
```diff
@@ -678,38 +682,64 @@ class Service {
...
+  ) => {
+    const onSwapFailed = (deal: SwapDeal) => {
       this.logger.trace(`notifying SwapFailure subscription for ${deal.rHash} with role ${SwapRole[deal.role]}`);
       // always alert client for maker matches, taker matches only when specified
       if (deal.role === SwapRole.Maker || args.includeTaker) {
         callback(deal as SwapFailure);
       }
-    });
+    };
+    this.swaps.on('swap.failed', onSwapFailed);
```
Comment (erkarl) [inline lib/service/Service.ts:740]:
```
const swapFailed$ = from(this.swaps, 'swap.failed').pipe(
  takeUntil(cancelled$),
);

swapFailed$.subscribe({
  next: onSwapFailed,
  error: this.logger.error,
});
```

**Comment by sangaman** [comment]
@erkarl I refactored the code using the rxjs approach and gave it another test, look it over again one more time if you can to ensure it looks right to you.

**Comment by sangaman** [comment]
Tests are failing now due to

```
--- FAIL: TestSecurity (171.17s)

    --- PASS: TestSecurity/network_initialization (0.29s)

    --- FAIL: TestSecurity/taker_stalling_on_swapAccepted (122.02s)

        tests-security.go:99: 

            	Error Trace:	tests-security.go:99

            	            				harnessTest.go:95

            	            				xud_test.go:222

            	Error:      	Received unexpected error:

            	            	timeout reached before event was received

            	Test:       	TestSecurity/taker_stalling_on_swapAccepted
```

This wasn't happening before the rxjs refactoring, so I'm going to go back to that commit and open a separate PR for the refactoring.
