### PR TITLE
fix: propagating nodes on database if initDB true even DB is filled

### LINKED ISSUE #1645: Seed node updates don't propagate on existing db
### Background

It looks like adding/changing seed nodes in the xud codebase does **not** propagate these in an existing xud database.

This is an environment that was created with `beta.3` and after xud upgrade to `beta.4` it did **not** attempt to connect to the newly added seed nodes (#1616 & #1623 ), just the existing one (which is down by now):
```
12/06/2020 09:12:16.319 [P2P] info: Connecting to known / previously connected peers
12/06/2020 09:12:18.583 [P2P] debug: Connected pre-handshake to 127.0.0.1:32768
12/06/2020 09:12:18.872 [P2P] debug: Peer 02e2fb25a63e6e1df25a883e3d19e8048131571808eba13e9ada68231625d1f8c0 (VersionUphold): closing socket. reason: ConnectedToSelf
12/06/2020 09:12:18.878 [P2P] warn: could not open connection to inbound peer (02e2fb25a63e6e1df25a883e3d19e8048131571808eba13e9ada68231625d1f8c0 (VersionUphold)): cannot attempt connection to self
12/06/2020 09:12:18.880 [P2P] info: Peer 02e2fb25a63e6e1df25a883e3d19e8048131571808eba13e9ada68231625d1f8c0 (VersionUphold) socket closed
12/06/2020 09:12:19.010 [P2P] verbose: Verified reachability of advertised address: et6vfjftixwa4dqqwvermffbyxqlu5utxovyp2dz7tcru7wov4r744qd.onion:18885
12/06/2020 09:12:35.801 [RPC] debug: received call /xudrpc.Xud/ListPeers
12/06/2020 09:12:38.965 [RPC] debug: received call /xudrpc.Xud/ListPeers
12/06/2020 09:12:44.678 [RPC] debug: received call /xudrpc.Xud/ListPeers
12/06/2020 09:12:46.330 [P2P] warn: could not open connection to outbound peer (037a74737630bb5a9979762b2163ef9f95c81e00caf347bacc17f16991cdbb61f7@xud1.testnet.exchangeunion.com:18885): could not connect to peer at xud1.testnet.exchangeunion.com:18885: Proxy connection timed out
12/06/2020 09:12:48.529 [RPC] debug: received call /xudrpc.Xud/ListPeers
Jun 12 09:12:50.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
12/06/2020 09:12:50.376 [P2P] warn: could not open connection to outbound peer (037a74737630bb5a9979762b2163ef9f95c81e00caf347bacc17f16991cdbb61f7@pso32ae2l5nyh3clgee2nj2hgpmcnluhaqibjm2r2fjcsn4gclxfmrid.onion:18885): could not connect to peer at pso32ae2l5nyh3clgee2nj2hgpmcnluhaqibjm2r2fjcsn4gclxfmrid.onion:18885: Socks5 proxy rejected connection - HostUnreachable
12/06/2020 09:12:50.380 [P2P] info: Completed start-up connections to known peers
```

### Your environment

* version of `xud`: `1.0.0-beta.4-43c03e7`
* which operating system (`uname -a` on *Nix): ubuntu 20.04 arm 64

### PR DESCRIPTION
**Pull request by rsercano**
attemps to resolve #1645

### CODE REVIEW

File: lib/db/DB.ts [hunk 1]
```diff
@@ -166,13 +166,20 @@ class DB {
...
-    if (shouldInitDb) {
+    if (initDb) {
       // initialize database with the seed nodes for the configured network
       const nodes = defaultNodes(network);
       if (nodes) {
-        await Node.bulkCreate(nodes);
+        const existingNodes = await Models.Node(this.sequelize).findAll();
+        const newNodes = nodes.filter(node => (!existingNodes.find(n => (n.nodePubKey === node.nodePubKey))));
+
+        if (newNodes) {
```
Comment (sangaman) [inline lib/db/DB.ts:176]: Arrays (even when empty) are truthy so this will always resolve to true, even when there are no nodes. Better to check `newNodes.length > 0`.

**Review by sangaman — CHANGES_REQUESTED** [review]
Looks like this should work to add any missing seed nodes to the database. I just noted one change to ensure we aren't calling `bulkCreate` every time we start xud even when there are no nodes to add.

File: lib/db/DB.ts (hunk 1 above)
Comment (rsercano) [reply lib/db/DB.ts:176]: True, sorry to overlook that, thanks!

**Review by raladev — APPROVED** [review]

**Review by erkarl — APPROVED** [review]
