### PR TITLE
fix(swaps): don't cancel invoice on swap timeout

### LINKED ISSUE #1574: Got free DAI because of failed swap from connext side
### Your environment

Taker's env - master of simnet docker setup
Maker's env - lndltc and connext are from master of simnet docker setup, but xud was installed natively and tradehistory branch was used.

### Steps to reproduce

1. ./xucli -p 28886 buy 0.2 LTC/DAI 200 1 as maker
2. sell 0.2 LTC/DAI 200 1 as taker

### Actual behaviour

1. msg about successful swap for taker;
2. 40 DAI is received by taker;
4. xud node died because of the assertion;
3. 0.2 LTC was in pending_htlcs for ~30 sec and after that it was returned to taker's channel (he did not pay for DAI).

### Screens
[balances_before_the_swap](https://user-images.githubusercontent.com/29906866/82675463-82420100-9c4d-11ea-8e53-6875a90d1425.png)
[swap_proccess](https://user-images.githubusercontent.com/29906866/82675461-81a96a80-9c4d-11ea-833c-aadc1aa25986.png)
[LTC_Returned_back_to_taker](https://user-images.githubusercontent.com/29906866/82675459-80783d80-9c4d-11ea-884e-1dae5edc15ee.png)

### Logs

Note: Some of logs can be bigger then others because of re-installation cycles, dont try to match startup phases of them.

22/05/2020 13:25 - approx. time of the swap for taker
22/05/2020 06:25 - approx. time of the swap for maker

[takers_log.zip](https://github.com/ExchangeUnion/xud/files/4668501/takers_log.zip)
[makers_log.zip](https://github.com/ExchangeUnion/xud/files/4668514/makers_log.zip)

UPD: Add missed connext log for maker.
[freedai_connext_maker.log](https://github.com/ExchangeUnion/xud/files/4676865/freedai_connext_maker.log)

### PR DESCRIPTION
**Pull request by sangaman**
This fixes a bug where we cancel the incoming invoice for swaps that time out as the maker. Although we would put the timed out swap into the SwapRecovery module, the swap cannot be recovered if the incoming invoice has been canceled, and if the taker later claims our payment it leaves us unable to claim the maker's payment.

The widely used `failDeal` method in Swaps was canceling incoming invoices which is what led to this unintended behavior. Now this logic is removed from `failDeal` - since it is only relevant when we attempt a payment as maker and it fails in a permanent fashion. Instead, we only cancel & remove the invoice for this specific case.

Fixes #1574.

### CODE REVIEW

**Comment by erkarl** [comment]
I'm still seeing the HTLC being cancelled:
```
25/05/2020 18:50:09.612 [SWAPS] debug: deal 00d6ceda3c058e11b058eb6461a1ee2d0c8dbf79c81b10a24fec87d6c6d62b30 failed due to SwapTimedOut
25/05/2020 18:50:09.614 [ORDERBOOK] debug: removed hold of 100000 on order 5ac989f0-9eb8-11ea-839e-df5d7bbeb8b0
25/05/2020 18:50:09.614 [SWAPS] debug: Sending SwapTimedOut error to peer: {"rHash":"00d6ceda3c058e11b058eb6461a1ee2d0c8dbf79c81b10a24fec87d6c6d62b30","failureReason":10}
25/05/2020 18:50:09.801 [SWAPS] debug: new deal error message for 00d6ceda3c058e11b058eb6461a1ee2d0c8dbf79c81b10a24fec87d6c6d62b30: + Timeout has occurred (ETH)
25/05/2020 18:50:09.803 [SWAPS] error: could not settle invoice: 7.4 - Timeout has occurred
25/05/2020 18:50:09.809 [LND-BTC] debug: canceled invoice for 00d6ceda3c058e11b058eb6461a1ee2d0c8dbf79c81b10a24fec87d6c6d62b30
25/05/2020 18:50:09.811 [LND-BTC] debug: deleted invoice subscription for 00d6ceda3c058e11b058eb6461a1ee2d0c8dbf79c81b10a24fec87d6c6d62b30
```

File: lib/swaps/Swaps.ts [hunk 1]
```diff
@@ -951,13 +951,30 @@ class Swaps extends EventEmitter {
...
+          // conclusive resolution
+          if (!this.swapRecovery.pendingSwaps.has(rHash)) {
+            const swapDealInstance = await this.repository.getSwapDeal(rHash);
+            this.swapRecovery.pendingSwaps.set(rHash, swapDealInstance!);
+          }
         } else {
+          // the payment failed permanently, so we remove our incoming invoice
+          // and fail the deal
+          const makerSwapClient = this.swapClientManager.get(deal.makerCurrency)!;
+          makerSwapClient.removeInvoice(deal.rHash).catch(this.logger.error); // we don't need to await the remove invoice call
```
Comment (erkarl) [inline lib/swaps/Swaps.ts:976]: Looks like the current `sendPayment` error is `7.4 - Timeout has occurred` so it's getting to this block.
