### PR TITLE
fix(swaps): validate Raiden's resolve request

### LINKED ISSUE #1149: Raiden lock time follow-ups
This tracks open issues persisting after #1082 for us to properly have swaps with raiden as the first leg.

The main issues for now are:

- `expiration` is currently an absolute block number, which can't be used by xud because we don't currently have a way to get to the ethereum block height. Passing in the height on the resolve request would allow us to calculate a delta.

- Ensure that raiden is properly setting the lock time. In testing with @erkarl, the values we got for the settle and reveal timeouts, as well as expiration, were lower than expected and lower than the `lock_timeout` we set on the raiden token payment call.

### PR DESCRIPTION
**Pull request by ghost**
In this commit we validate Raiden's resolve request to make sure the
payment we're receiving has the previously agreed upon `deal.makerCltvDelta` as the
minimum duration of the lock.

In addition we change the error handling to return a status code 400
(Bad Request) to prevent Raiden from crashing. Previously we returned a
status code of 200 with the response of `{ secret: 'error message' }`.

Closes: https://github.com/ExchangeUnion/xud/issues/1149

### CODE REVIEW

**Comment by kilrau** [comment]
Please open an issue on raiden side for the crash @erkarl

**Comment by erkarl** [comment]
> Please open an issue on raiden side for the crash @erkarl

There already is: https://github.com/ExchangeUnion/raiden/issues/1

**Comment by kilrau** [comment]
I successfully tested this branch on native simnet, which since ExchangeUnion/xud#1080 changed the behaviour of the XUD resolver when it gets an unfamiliar rHash and caused raiden to crash. With this branch, this is handled gracefully and raiden doesn't crash.

File: lib/raidenclient/types.ts [hunk 1]
```diff
@@ -68,6 +68,7 @@ export type RaidenResolveRequest = {
   reveal_timeout: number;
```
Comment (sangaman) [inline lib/raidenclient/types.ts]: Should we be removing reveal and settle timeout as part of this PR? Or are you planning to do this separately? I'm thinking if it's done together this can be marked as closing #1149.

If so, you can also remove the commented out "unused" fields below.

File: lib/http/HttpServer.ts [hunk 2]
```diff
@@ -67,7 +67,10 @@ class HttpServer {
       res.writeHead(200, { 'Content-Type': 'application/json' });
       res.end(JSON.stringify(resJson));
     } catch (err) {
-      if (err.code === errorCodes.INVALID_ARGUMENT) {
+      if (
+        err.code === errorCodes.INVALID_ARGUMENT ||
+        err.code === swapErrorCodes.INVALID_RESOLVE_REQUEST
```
Comment (sangaman) [inline lib/http/HttpServer.ts]: I'm thinking I should've made this a `switch` statement when I wrote this originally, but now I think it's even more clearly the nicer choice. Would you mind rewriting these if/elses as a switch?

**Review by sangaman — COMMENTED** [review]
Looks nice, the 400/404/500 HTTP error codes here are much more sensible than returning plain error message strings in place of the preimage. Just a few questions/suggestions below.

File: lib/raidenclient/types.ts (hunk 1 above)
Comment (erkarl) [reply lib/raidenclient/types.ts]: Yes, absolutely - good idea.

File: lib/http/HttpServer.ts (hunk 2 above)
Comment (erkarl) [reply lib/http/HttpServer.ts]: Rewrote this as switch - looks much better now, thanks.

File: lib/http/HttpServer.ts [hunk 3]
```diff
@@ -67,15 +67,22 @@ class HttpServer {
...
-        res.end(err.message);
-      } else {
-        res.writeHead(500);
-        res.end(JSON.stringify(err));
+      switch (err.code) {
+        case errorCodes.INVALID_ARGUMENT:
+          res.writeHead(400);
+          res.end(err.message);
+          break;
+        case swapErrorCodes.INVALID_RESOLVE_REQUEST:
```
Comment (sangaman) [inline lib/http/HttpServer.ts]: This can just flow with the previous case like so we don't need to write the code twice:

```javascript
        case errorCodes.INVALID_ARGUMENT:
        case swapErrorCodes.INVALID_RESOLVE_REQUEST:
          res.writeHead(400);
          res.end(err.message);
          break;
```

File: lib/http/HttpServer.ts [hunk 4]
```diff
@@ -67,15 +67,22 @@ class HttpServer {
...
+          res.writeHead(400);
+          res.end(err.message);
+          break;
+        case swapErrorCodes.PAYMENT_HASH_NOT_FOUND:
+          res.writeHead(404);
+          res.end(err.message);
+          break;
+        default:
+          res.writeHead(500);
+          res.end(JSON.stringify(err));
```
Comment (sangaman) [inline lib/http/HttpServer.ts]: So a `break` here for the last case is not technically necessary, but I kind of like it anyway in case the cases ever get reordered or if we add another case at the end and forget to add the `break`.

There's actually a [tslint rule](https://palantir.github.io/tslint/rules/switch-final-break/) for this I just found that I think might be worth adding, I believe we have the final `break` in use elsewhere in the code so it would only enforce this rule going forward.

**Review by sangaman — CHANGES_REQUESTED** [review]
Thanks, one last (or maybe two) change re: the new switch statement then this should be good to merge.

File: tslint.json [hunk 5]
```diff
@@ -67,6 +67,8 @@
       }
     ],
     "one-line": [true, "check-catch", "check-finally", "check-open-brace", "check-whitespace"],
-    "no-switch-case-fall-through": true
+    "no-switch-case-fall-through": true,
+    "switch-final-break": [true, "always"]
+
```
Comment (sangaman) [inline tslint.json]: Extra blank line here.

**Review by sangaman — APPROVED** [review]
Looks good! Do you think you could put the tslint rule in a separate commit tho?

**Review by moshababo — APPROVED** [review]

**Comment by michael1011** [comment]
@erkarl @sangaman could you please revisit this PR and merge it asap? The raiden in my local simnet instance is crashing a lot which causes some issues with the balancing of the initial deposit.

**Review by michael1011 — APPROVED** [review]

**Review by sangaman — APPROVED** [review]
