### PR TITLE
fix: alias missing in streamorders (#1725)

### LINKED ISSUE #1725: No alias in streamorders stream messages
### Actual behaviour

Empty Alias filed in streamorders messages
[Screenshot from 2020-07-13 20-28-19](https://user-images.githubusercontent.com/29906866/87336026-ebf1d380-c549-11ea-8d12-ea109f967a4c.png)

### Expected behaviour

Not empty Alias field

### PR DESCRIPTION
**Pull request by rsercano**
resolves #1725 

image

### CODE REVIEW

**Review by raladev — DISMISSED** [review]

File: lib/service/Service.ts [hunk 1]
```diff
@@ -694,13 +694,20 @@ class Service extends EventEmitter {
...
+          callback(order);
+        };
+      }
+
       this.orderBook.pairIds.forEach((pair) => {
         const ownOrders = this.orderBook.getOwnOrders(pair);
         const peerOrders = this.orderBook.getPeersOrders(pair);
         ownOrders.buyArray.forEach(order => callback(order));
-        peerOrders.buyArray.forEach(order => callback(order));
+        peerOrders.buyArray.forEach(setAlias(this.pool));
```
Comment (sangaman) [inline lib/service/Service.ts:708]: There already is a method in the Service class (`toServiceOrder`) that sets the alias on the order objects returned by these calls, I think it makes sense to reuse that here.

```
ownOrders.buyArray.forEach(order => callback(this.toServiceOrder(order, false)));
peerOrders.buyArray.forEach(order => callback(this.toServiceOrder(order, true)));
ownOrders.sellArray.forEach(order => callback(this.toServiceOrder(order, false)));
peerOrders.sellArray.forEach(order => callback(this.toServiceOrder(order, true)));
```

Then we don't need to make changes to any of the internal order types nor to existing tests.

I also think we need to make the same change to the `orderAdded$.subscribe` call, as it is now I don't believe it would return aliases for newly added orders that happen after the order subscription has begun. There we should do:

```
next: order => callback(this.toServiceOrder(order, true)),
```

**Review by sangaman — CHANGES_REQUESTED** [review]
See below for reusing existing logic for this fix. I also don't think the current implementation would set aliases on newly added orders after the subscription has been created.

File: lib/service/Service.ts (hunk 1 above)
Comment (rsercano) [reply lib/service/Service.ts]: Thanks for detailed explanation @sangaman you literally implemented this instead of me.

**Review by raladev — DISMISSED** [review]
works
```
Successfully connected, subscribing for orders
Order added: {"price":0.02751644,"quantity":1410750000,"pairId":"ETH/BTC","id":"261f1141-1dd2-11eb-b5b4-63796ea33ed7","nodeIdentifier":{"nodePubKey":"03df4f36fa35bd242263e8d09d6b422108dab1f08d91237bb3aa2dad957cf08a71","alias":"SheriffSolution"},"localId":"","createdAt":1604407802678,"side":0,"isOwnOrder":false,"hold":0}
Order added: {"price":0.02850492,"quantity":1321787337,"pairId":"ETH/BTC","id":"675bc750-1dbb-11eb-b5b4-63796ea33ed7","nodeIdentifier":{"nodePubKey":"03df4f36fa35bd242263e8d09d6b422108dab1f08d91237bb3aa2dad957cf08a71","alias":"SheriffSolution"},"localId":"","createdAt":1604407802680,"side":1,"isOwnOrder":false,"hold":0}
Order added: {"price":0.004,"quantity":1000000000,"pairId":"LTC/BTC","id":"ee8518e0-12b6-11eb-b3e8-7f316282c8c8","nodeIdentifier":{"nodePubKey":"03ece33a30db1dbce4b62fa96a5e9541138a24997ef5672eebed2d332270e39542","alias":"OzoneYellow"},"localId":"","createdAt":1604407802517,"side":0,"isOwnOrder":false,"hold":0}
Order added: {"price":0.0042,"quantity":990000000,"pairId":"LTC/BTC","id":"f8e13a30-12b6-11eb-b3e8-7f316282c8c8","nodeIdentifier":{"nodePubKey":"03ece33a30db1dbce4b62fa96a5e9541138a24997ef5672eebed2d332270e39542","alias":"OzoneYellow"},"localId":"","createdAt":1604407802519,"side":1,"isOwnOrder":false,"hold":0}
Order added: {"price":4,"quantity":200000000,"pairId":"USDT/DAI","id":"6ed43cc0-1dd3-11eb-84f1-87162f5eadf7","localId":"1","createdAt":1604407949964,"side":0,"isOwnOrder":true,"hold":0}
Order removed: {"quantity":1000000000,"pairId":"LTC/BTC","orderId":"ee8518e0-12b6-11eb-b3e8-7f316282c8c8","localId":"","isOwnOrder":false}
Order removed: {"quantity":990000000,"pairId":"LTC/BTC","orderId":"f8e13a30-12b6-11eb-b3e8-7f316282c8c8","localId":"","isOwnOrder":false}
Order added: {"price":0.004,"quantity":1000000000,"pairId":"LTC/BTC","id":"ee8518e0-12b6-11eb-b3e8-7f316282c8c8","nodeIdentifier":{"nodePubKey":"03ece33a30db1dbce4b62fa96a5e9541138a24997ef5672eebed2d332270e39542","alias":"OzoneYellow"},"localId":"","createdAt":1604407994753,"side":0,"isOwnOrder":false,"hold":0}
Order added: {"price":0.0042,"quantity":990000000,"pairId":"LTC/BTC","id":"f8e13a30-12b6-11eb-b3e8-7f316282c8c8","nodeIdentifier":{"nodePubKey":"03ece33a30db1dbce4b62fa96a5e9541138a24997ef5672eebed2d332270e39542","alias":"OzoneYellow"},"localId":"","createdAt":1604407994758,"side":1,"isOwnOrder":false,"hold":0}
```

**Review by erkarl — APPROVED** [review]

File: lib/grpc/GrpcService.ts [hunk 2]
```diff
@@ -63,6 +63,28 @@ const createOrder = (order: Order) => {
   return grpcOrder;
 };
 
+const createOrderFromServiceOrder = (order: ServiceOrder) => {
```
Comment (sangaman) [inline lib/grpc/GrpcService.ts:66]: This method isn't necessary either, you can just use the existing `createServiceOrder` in its place.

File: lib/grpc/GrpcService.ts [hunk 3]
```diff
@@ -880,10 +902,10 @@ class GrpcService {
 
     const cancelled$ = getCancelled$(call);
 
-    this.service.subscribeOrders(call.request.toObject(), (order?: Order, orderRemoval?: OrderPortion) => {
+    this.service.subscribeOrders(call.request.toObject(), (order?: ServiceOrder, orderRemoval?: OrderPortion) => {
       const orderUpdate = new xudrpc.OrderUpdate();
       if (order) {
-        orderUpdate.setOrder(createOrder(order));
+        orderUpdate.setOrder(createOrderFromServiceOrder(order));
```
Comment (sangaman) [inline lib/grpc/GrpcService.ts:908]: `createServiceOrder(order)`

**Review by sangaman — CHANGES_REQUESTED** [review]
One last small thing to prevent duplicate code/methods.

**Comment by rsercano** [comment]
Yes sorry I overlooked it @sangaman

**Review by sangaman — APPROVED** [review]
Looks good, thanks for seeing this through!

**Comment by kilrau** [comment]
Test and merge honor is with you @raladev

**Review by raladev — APPROVED** [review]
