### PR TITLE
fix(swaps): set cltvLimit correctly

### LINKED ISSUE #1158: cltvLimit is set incorrectly
@offerm's debugging result:
> The maker is doing queryroute to get the route cltv (LTC) it adds a buffer 144*4. In out case the result is 1312. Maker convers it to BTC blocks (328) and sends to taker. When maker is making the second leg payment the cltvLimit should be 1312 (LTC blocks) and not 328 (BTC blocks). With 328, LND fails to find a route for the send payment

### PR DESCRIPTION
**Pull request by sangaman**
Fixes #1158.

This fixes a bug whereby the `makerCltvDelta` was erroneously used for the `cltvLimit` for the payment from maker to taker. `makerCltvDelta` is irrelevent to the payment to the taker. Instead, this value is set to the time lock of the route found from maker to taker for lnd, raiden currently has no equivalent to `cltvLimit`.

In tests, payments would still fail occasionally due to no route found. Adding 3 blocks to the `cltvLimit` value consistently resolved these failures - any fewer than 3 and the payments would still fail. More investigation is warranted into why this is necessary, it's possible that there is a bug in the `cltvLimit` implementation within lnd.

This fix makes the new multihop simulation test case in #1160 pass.

### CODE REVIEW

**Comment by kilrau** [comment]
Definitely needs your review @offerm

File: lib/raidenclient/RaidenClient.ts [hunk 1]
```diff
@@ -165,26 +165,28 @@ class RaidenClient extends SwapClient {
...
-    let amount = 0;
-    let tokenAddress;
+    let amount: number;
+    let tokenAddress: string;
+    let lock_timeout: number | undefined;
     if (deal.role === SwapRole.Maker) {
       // we are the maker paying the taker
       amount = deal.takerUnits;
-      tokenAddress = this.tokenAddresses.get(deal.takerCurrency);
+      tokenAddress = this.tokenAddresses.get(deal.takerCurrency)!;
```
Comment (erkarl) [inline lib/raidenclient/RaidenClient.ts]: I think we also need to use `lock_timout=deal.takerMaxTimeLock` here to ensure that the maker's payment duration.

Comment (sangaman) [reply lib/raidenclient/RaidenClient.ts]: I don't think so, because we're using `lock_timeout` as the delay extended to the recipient of the payment, whereas the `takerMaxTimeLock` is an upper bound on the total delay for the route. Also when the maker to taker payment is raiden, we use a hardcoded value for the route total time lock of 101 (which is then set to `takerMaxTimelock`) so I don't think it would be of much use here anyway.

Still, this is a good point to consider going forward, if we're going to be using multihop raiden payments with variable total time locks then we need to know what the maximum time lock will be for properly executing the swap.

Comment (erkarl) [reply lib/raidenclient/RaidenClient.ts]: Ah, right - makes sense. I forgot that we're only supporting direct channels for now.

Comment (kilrau) [reply lib/raidenclient/RaidenClient.ts]: > Still, this is a good point to consider going forward, if we're going to be using multihop raiden payments with variable total time locks then we need to know what the maximum time lock will be for properly executing the swap.

Please open an issue for this with https://github.com/ExchangeUnion/xud/issues/1068 as dependency @sangaman
