### PR TITLE
fix: don't send order invalidation to taker

### LINKED ISSUE #478: Order removed twice on match
Right now, when we match an order as the taker, we wind up trying to remove the order twice. Once on match locally, and then once again when the maker broadcasts an order invalidation packet. We should still remove orders on local match, but we need to either not send the order invalidation packet to the taker or have the taker handle it gracefully without logging an error message.

### LINKED ISSUE #506: cancel order failure on partial taking
See what I did and what I got.

```
admins-MacBook-Pro-2:xud admin$ ./bin/xucli -p 7002 connect 0235584e2ac9a34a13ce6f6dc9fb8aa1e7918d7701f0b4b69dc002887e6b3fbba3@localhost:8885
(node:70263) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
success
```
```
admins-MacBook-Pro-2:xud admin$ ./bin/xucli -p 7001 buy 0.004 LTC/BTC  0.96
(node:70264) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
{
  "matchesList": [],
  "remainingOrder": {
    "price": 0.96,
    "quantity": 0.004,
    "pairId": "LTC/BTC",
    "peerPubKey": "",
    "id": "762937e1-bc92-11e8-9f43-a5047fcd0223",
    "localId": "762937e0-bc92-11e8-9f43-a5047fcd0223",
    "createdAt": 1537419786846,
    "invoice": "",
    "canceled": false
  }
}
```
```
admins-MacBook-Pro-2:xud admin$ ./bin/xucli -p 7002 sell 0.003 LTC/BTC  market
(node:70265) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
{
  "matchesList": [
    {
      "maker": {
        "price": 0.96,
        "quantity": 0.003,
        "pairId": "LTC/BTC",
        "peerPubKey": "0235584e2ac9a34a13ce6f6dc9fb8aa1e7918d7701f0b4b69dc002887e6b3fbba3",
        "id": "762937e1-bc92-11e8-9f43-a5047fcd0223",
        "localId": "",
        "createdAt": 1537419786848,
        "invoice": "",
        "canceled": false
      },
      "taker": {
        "price": 0,
        "quantity": -0.003,
        "pairId": "LTC/BTC",
        "peerPubKey": "",
        "id": "77c18b21-bc92-11e8-a8e6-a7e8fdc9cfa2",
        "localId": "77c18b20-bc92-11e8-a8e6-a7e8fdc9cfa2",
        "createdAt": 1537419789522,
        "invoice": "",
        "canceled": false
      }
    }
  ]
}
```

```
9/20/2018, 8:03:09 AM [ORDERBOOK] debug: order match: {"maker":{"pairId":"LTC/BTC","price":0.96,"quantity":0.003,"id":"762937e1-bc92-11e8-9f43-a5047fcd0223","peerPubKey":"0235584e2ac9a34a13ce6f6dc9fb8aa1e7918d7701f0b4b69dc002887e6b3fbba3","createdAt":1537419786848},"taker":{"pairId":"LTC/BTC","price":0,"quantity":-0.003,"localId":"77c18b20-bc92-11e8-a8e6-a7e8fdc9cfa2","id":"77c18b21-bc92-11e8-a8e6-a7e8fdc9cfa2","createdAt":1537419789522}}
9/20/2018, 8:03:09 AM [SWAPS] debug: New deal: {"takerCurrency":"BTC","makerCurrency":"LTC","takerAmount":288000,"makerAmount":300000,"takerCltvDelta":144,"r_hash":"6acb27197517d5a12d7c7be554b985df0acee87555e78e00d2cac3c30483a220","orderId":"762937e1-bc92-11e8-9f43-a5047fcd0223","pairId":"LTC/BTC","proposedQuantity":-0.003,"phase":0,"state":0,"stateReason":"","r_preimage":"4536dda6537b626146d99f79751bfa7d447a387aba6c0ea038359be951852909","myRole":0,"createTime":1537419789524}
9/20/2018, 8:03:09 AM [SWAPS] debug: Requesting deal: {"takerCurrency":"BTC","makerCurrency":"LTC","takerAmount":288000,"makerAmount":300000,"takerCltvDelta":144,"r_hash":"6acb27197517d5a12d7c7be554b985df0acee87555e78e00d2cac3c30483a220","orderId":"762937e1-bc92-11e8-9f43-a5047fcd0223","pairId":"LTC/BTC","proposedQuantity":-0.003,"phase":0,"state":0,"stateReason":"","r_preimage":"4536dda6537b626146d99f79751bfa7d447a387aba6c0ea038359be951852909","myRole":0,"createTime":1537419789524}
9/20/2018, 8:03:09 AM [P2P] debug: received swapResponse from 0235584e2ac9a34a13ce6f6dc9fb8aa1e7918d7701f0b4b69dc002887e6b3fbba3: {"makerCltvDelta":1152,"r_hash":"6acb27197517d5a12d7c7be554b985df0acee87555e78e00d2cac3c30483a220","quantity":-0.003}
9/20/2018, 8:03:09 AM [SWAPS] info: ResolveHash starting with hash: 6acb27197517d5a12d7c7be554b985df0acee87555e78e00d2cac3c30483a220
9/20/2018, 8:03:09 AM [SWAPS] debug: Executing taker code
9/20/2018, 8:03:09 AM [SWAPS] debug: Amount received for preImage 4536dda6537b626146d99f79751bfa7d447a387aba6c0ea038359be951852909
9/20/2018, 8:03:10 AM [P2P] verbose: canceled order from 0235584e2ac9a34a13ce6f6dc9fb8aa1e7918d7701f0b4b69dc002887e6b3fbba3: {"orderId":"762937e1-bc92-11e8-9f43-a5047fcd0223","pairId":"LTC/BTC"}
{ AssertionError [ERR_ASSERTION]: order quantity must equal quantityToDecrease
    at OrderBook.removePeerOrder (/Users/admin/github/xud/dist/orderbook/OrderBook.js:259:33)
    at Pool.pool.on.order (/Users/admin/github/xud/dist/orderbook/OrderBook.js:50:72)
    at Pool.emit (events.js:182:13)
    at Pool.<anonymous> (/Users/admin/github/xud/dist/p2p/Pool.js:275:26)
    at Generator.next (<anonymous>)
    at /Users/admin/github/xud/dist/p2p/Pool.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/admin/github/xud/dist/p2p/Pool.js:3:12)
    at Pool.handlePacket (/Users/admin/github/xud/dist/p2p/Pool.js:264:47)
    at Pool.<anonymous> (/Users/admin/github/xud/dist/p2p/Pool.js:394:28)
    at Generator.next (<anonymous>)
    at /Users/admin/github/xud/dist/p2p/Pool.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/admin/github/xud/dist/p2p/Pool.js:3:12)
    at Peer.peer.on (/Users/admin/github/xud/dist/p2p/Pool.js:393:43)
    at Peer.emit (events.js:182:13)
    at Parser.Peer.handlePacket (/Users/admin/github/xud/dist/p2p/Peer.js:376:30)
    at Parser.emit (events.js:182:13)
    at Parser.parsePacket (/Users/admin/github/xud/dist/p2p/Parser.js:100:22)
    at Parser.feed (/Users/admin/github/xud/dist/p2p/Parser.js:91:22)
    at Socket.socket.on (/Users/admin/github/xud/dist/p2p/Peer.js:324:29)
    at Socket.emit (events.js:182:13)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
/Users/admin/github/xud/dist/bootstrap.js:13
        throw err;
        ^

AssertionError [ERR_ASSERTION]: order quantity must equal quantityToDecrease
    at OrderBook.removePeerOrder (/Users/admin/github/xud/dist/orderbook/OrderBook.js:259:33)
    at Pool.pool.on.order (/Users/admin/github/xud/dist/orderbook/OrderBook.js:50:72)
    at Pool.emit (events.js:182:13)
    at Pool.<anonymous> (/Users/admin/github/xud/dist/p2p/Pool.js:275:26)
    at Generator.next (<anonymous>)
    at /Users/admin/github/xud/dist/p2p/Pool.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/admin/github/xud/dist/p2p/Pool.js:3:12)
    at Pool.handlePacket (/Users/admin/github/xud/dist/p2p/Pool.js:264:47)
    at Pool.<anonymous> (/Users/admin/github/xud/dist/p2p/Pool.js:394:28)
    at Generator.next (<anonymous>)
    at /Users/admin/github/xud/dist/p2p/Pool.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/admin/github/xud/dist/p2p/Pool.js:3:12)
    at Peer.peer.on (/Users/admin/github/xud/dist/p2p/Pool.js:393:43)
    at Peer.emit (events.js:182:13)
    at Parser.Peer.handlePacket (/Users/admin/github/xud/dist/p2p/Peer.js:376:30)
    at Parser.emit (events.js:182:13)
    at Parser.parsePacket (/Users/admin/github/xud/dist/p2p/Parser.js:100:22)
    at Parser.feed (/Users/admin/github/xud/dist/p2p/Parser.js:91:22)
    at Socket.socket.on (/Users/admin/github/xud/dist/p2p/Peer.js:324:29)
    at Socket.emit (events.js:182:13)

```

### PR DESCRIPTION
**Pull request by sangaman**
This commit fixes a bug where a a maker sends an invalidation packet to the taker after an order is executed. The taker will have already adjusted the orderbook locally upon successful execution, resulting in
a duplicate attempt. This fix makes it so makers don't send invalidation
packets to takers.

Fixes #506. Fixes #478.

### CODE REVIEW

File: lib/p2p/Pool.ts [hunk 1]
```diff
@@ -314,9 +314,17 @@ class Pool extends EventEmitter {
...
+  /**
+   * Broadcasts an [[OrderInvalidationPacket]] to all currently connected peers.
+   * @param nodeToExclude the node pub key of a node to exclude from the packet broadcast
+   */
+  public broadcastOrderInvalidation = (order: OrderIdentifier, nodeToExclude?: string) => {
     const orderInvalidationPacket = new packets.OrderInvalidationPacket(order);
-    this.peers.forEach(peer => peer.sendPacket(orderInvalidationPacket));
+    this.peers.forEach((peer) => {
+      if (nodeToExclude && peer.nodePubKey !== nodeToExclude) {
+        peer.sendPacket(orderInvalidationPacket);
```
Comment (moshababo) [inline lib/p2p/Pool.ts]: It looks like that if `nodeToExclude` isn't specified, you won't send the packet to any of the peers

Comment (sangaman) [reply lib/p2p/Pool.ts]: Thanks for catching, silly mistake. I'd only tested this with 2 parties where the other party is always the taker.
