### PR TITLE
fix: swap sent/received amounts in satoshis

### LINKED ISSUE #1063: SWAP BTC/DAI went good but CLI failed
```
xud@xud-test-3:~/scripts/raiden$ xucli sell 0.001 BTC/DAI 11000
Error: 13 INTERNAL: Assertion failed
xud@xud-test-3:~/scripts/raiden$ 
```

Log files on test1 and test3 shows swap success
```
24/06/2019 21:51:47.200 [RPC] debug: received call /xudrpc.Xud/PlaceOrderSync
24/06/2019 21:51:47.202 [ORDERBOOK] debug: reduced order 43d5d910-96c6-11e9-a81c-cfff346a5cdd by 100000 quantity while matching order 43874710-96ca-11e9-ae4c-3fc0f3e079c4
24/06/2019 21:51:47.203 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker 43874710-96ca-11e9-ae4c-3fc0f3e079c4 and maker 43d5d910-96c6-11e9-a81c-cfff346a5cdd for 100000
24/06/2019 21:51:47.211 [LND-BTC] debug: got 1 route(s) to destination 03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a: 1903,,100000,1671257674285057,2500000000,100000,,1903,100000000,,03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a,,100000000, finalCltvDelta: 144
24/06/2019 21:51:47.212 [SWAPS] debug: New deal: {"takerCltvDelta":1,"rHash":"de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c","orderId":"43d5d910-96c6-11e9-a81c-cfff346a5cdd","pairId":"BTC/DAI","proposedQuantity":100000,"rPreimage":"3b89f60d6f08d8a90409345fd41d980e5b2cdc003bd57064bfed48ed4a7915aa","takerCurrency":"DAI","makerCurrency":"BTC","takerAmount":11000000000000000000,"makerAmount":100000,"destination":"03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a","peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","localId":"43874710-96ca-11e9-ae4c-3fc0f3e079c4","price":11000,"isBuy":true,"phase":0,"state":0,"role":0,"createTime":1561413107212}
24/06/2019 21:51:47.214 [SWAPS] debug: Requesting deal: {"takerCltvDelta":1,"rHash":"de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c","orderId":"43d5d910-96c6-11e9-a81c-cfff346a5cdd","pairId":"BTC/DAI","proposedQuantity":100000,"rPreimage":"3b89f60d6f08d8a90409345fd41d980e5b2cdc003bd57064bfed48ed4a7915aa","takerCurrency":"DAI","makerCurrency":"BTC","takerAmount":11000000000000000000,"makerAmount":100000,"destination":"03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a","peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","localId":"43874710-96ca-11e9-ae4c-3fc0f3e079c4","price":11000,"isBuy":true,"phase":0,"state":0,"role":0,"createTime":1561413107212}
24/06/2019 21:51:47.246 [P2P] debug: received swapAccepted from 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6: {"rHash":"de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c","quantity":100000,"makerCltvDelta":144}
24/06/2019 21:51:47.249 [LND-BTC] debug: executing sendPaymentSync -
          destination: 03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a, rHash: de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c, amount: 100000, FinalCltvDelta: 144
24/06/2019 21:51:47.823 [HTTP] debug: http server request json: {"token":"0x76671a2831dc0af53b09537dea57f1e22899655d","secrethash":"0xde1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c","amount":11000000000000000000,"payment_identifier":4079280201333692,"payment_sender":"0x7ed0299fa1ada71d10536b866231d447cdfa48b9","expiration":2131427,"payment_recipient":"0x283ead0338f8c202b996146d77a542fdfb60d437","reveal_timeout":50,"settle_timeout":500}
24/06/2019 21:51:47.824 [SWAPS] debug: handleResolveRequest starting with hash de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c
24/06/2019 21:51:47.828 [SWAPS] debug: Executing taker code to resolve hash
24/06/2019 21:51:47.829 [SWAPS] debug: Amount received for deal with payment hash 3b89f60d6f08d8a90409345fd41d980e5b2cdc003bd57064bfed48ed4a7915aa
24/06/2019 21:51:47.888 [ORDERBOOK] info: match executed on taker 43874710-96ca-11e9-ae4c-3fc0f3e079c4 and maker 43d5d910-96c6-11e9-a81c-cfff346a5cdd for 100000 with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6
24/06/2019 21:51:48.749 [SWAPS] debug: Swap completed. preimage = 3b89f60d6f08d8a90409345fd41d980e5b2cdc003bd57064bfed48ed4a7915aa
24/06/2019 21:51:48.750 [SWAPS] debug: Sending swap complete to peer: {"rHash":"de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c"}
```

### PR DESCRIPTION
**Pull request by sangaman**
Fixes #1063.

This scales the `amountReceived`, `amountSent`, `makerAmount`, and `takerAmount` fields to always be denominated in satoshis, even for currencies where the smallest unit is smaller than  a satoshi. In their place this adds `takerUnits` and `makerUnits` to the `SwapDeal` type to track the amounts in each currency's base unit for sending & receiving.

This prevents errors on the rpc layer, where amounts in wei can easily exceed the limits of `int64`. It also prevents issues in storing these values in the database, where these fields are likewise represented as 64 bit integers.

This also renames several enum values to use the word "Payment" instead of "Amount" (as in "PaymentReceived") to avoid any possible confusion since "amount" is typically used to refer to a number.

### CODE REVIEW

**Comment by sangaman** [comment]
I'm having trouble setting up the raiden channels to manually test the case of a large DAI order swap, @erkarl or @offerm if you're set up to do so could you give this branch a quick test? Thanks.

File: lib/swaps/Swaps.ts [hunk 1]
```diff
@@ -102,16 +104,20 @@ class Swaps extends EventEmitter {
...
+    const baseCurrencyUnits = Math.floor(baseCurrencyAmount * Swaps.UNITS_PER_CURRENCY[baseCurrency]);
+    const quoteCurrencyUnits = Math.floor(quoteCurrencyAmount * Swaps.UNITS_PER_CURRENCY[quoteCurrency]);
 
     const inboundCurrency = isBuy ? baseCurrency : quoteCurrency;
     const inboundAmount = isBuy ? baseCurrencyAmount : quoteCurrencyAmount;
+    const inboundUnits = isBuy ? baseCurrencyUnits : quoteCurrencyUnits;
     const outboundCurrency = isBuy ? quoteCurrency : baseCurrency;
     const outboundAmount = isBuy ? quoteCurrencyAmount : baseCurrencyAmount;
-    return { inboundCurrency, inboundAmount, outboundCurrency, outboundAmount };
+    const outboundUnits = isBuy ? quoteCurrencyAmount : baseCurrencyAmount;
```
Comment (erkarl) [inline lib/swaps/Swaps.ts]: I believe this is incorrect. Did you mean `quoteCurrencyUnits` and `baseCurrencyUnits`?

**Comment by erkarl** [comment]
I also think we need to adjust the `swapClient.getRoutes` arguments to use units instead of amounts.

File: lib/swaps/Swaps.ts (hunk 1 above)
Comment (sangaman) [reply lib/swaps/Swaps.ts]: Yes that's right, good catch.

**Comment by sangaman** [comment]
I updated according to the feedback, and also updated the calls to `addInvoice` to use units as well instead of amounts.

**Comment by sangaman** [comment]
Added a test case and squashed commits, thanks.
