### PR TITLE
fix(swaps): failed payment for completed swap

### LINKED ISSUE #1569: taker xud crashes after payment received
Based on: https://github.com/ExchangeUnion/xud-docker/pull/464#issuecomment-630986211

1. taker sent BTC payment
2. taker received ERC20 payment (revealing the preimage)
3. maker was unable to claim the payment
4. after some time taker's xud crashed

### PR DESCRIPTION
**Pull request by sangaman**
This handles an edge case described below that causes xud to crash due to an assertion error when a payment fails as taker for a swap that has already completed, as described below.

1. Taker sends payment.
2. Maker sees payment, and sends payment to Taker.
3. Taker receives payment, and marks the swap as complete.
4. Maker fails to claim payment, so the attempt to send payment (from step 1) fails.
5. Error handling logic when Taker's payment attempt doesn't go through causes it to "fail" the deal.
6. But the swap actually succeeded - from Taker's perspective - in step 3, and Taker hits an assertion error trying to fail a deal that has completed.

Fixes #1569.

### CODE REVIEW

**Comment by kilrau** [comment]
image
:heart:

File: lib/swaps/Swaps.ts [hunk 1]
```diff
@@ -759,6 +759,13 @@ class Swaps extends EventEmitter {
     try {
```
Comment (erkarl) [inline lib/swaps/Swaps.ts:759]: nit: I'm wondering if it's worth extracting this try/catch block into `sendMakerPayment(swapClient, deal)` and unit test the catch block behaviour?

**Comment by erkarl** [comment]
Simtests were failing - restarted the job.

File: lib/swaps/Swaps.ts (hunk 1 above)
Comment (sangaman) [reply lib/swaps/Swaps.ts:759]: It's a fine idea, but I just took a stab at this and it involved quite a bit of mocking. Perhaps in another PR? Or if you have an approach in mind maybe you can take a stab at it. It would be good to have a test for the `PAYMENT_REJECTED` error as well.

**Comment by sangaman** [comment]
> Simtests were failing - restarted the job.

They were failing because the custom-xud patch needed to be updated. I just took care of that, so they should pass now.

**Comment by raladev** [comment]
I dont think that this thing can be tested manually for now.
Can we add sim tests for that and similar cases like performing actions with completed swaps, filled/removed orders?
@kilrau @LePremierHomme

**Comment by kilrau** [comment]
> I dont think that this thing can be tested manually for now.
> Can we add sim tests for that and similar cases like performing actions with completed swaps, filled/removed orders?
> @kilrau @LePremierHomme

Yes, opened: https://github.com/ExchangeUnion/xud/issues/1573
