### PR TITLE
fix: added new grpc method to easily cancel all orders

### LINKED ISSUE #1878: Easy way to cancel orders in CLI
As CLI user I am missing an easy way to cancel my own orders. Right now I have to `xucli listorders -j`, find my order and the its ID and copy paste it into `xucli removeorder <id>` which is tedious right now and will be nearly impossible to do once there are more orders on the network

### PR DESCRIPTION
**Pull request by rsercano**
attempts to resolve #1878 

Sorry to implement this prior p1 ones, I had already started this, so wanted to complete first. 

image

### CODE REVIEW

File: lib/orderbook/OrderBook.ts [hunk 1]
```diff
@@ -816,6 +816,23 @@ class OrderBook extends EventEmitter {
     return order;
   }
 
+  public removeOwnOrders = () => {
+    const successfullyRemovedOrderIds = [];
+    const failedToRemovedOrderIds = [];
+
+    for (const localId of Array.from(this.localIdMap.keys())) {
+      try {
+        this.logger.debug(`Trying to remove order with id: ${localId}`);
```
Comment (sangaman) [inline lib/orderbook/OrderBook.ts:825]: I think this logging statement should be removed, or at most be set to `trace`, since there are other logging statements when the orders are actually removed.

File: proto/xudrpc.proto [hunk 2]
```diff
@@ -732,6 +743,15 @@ message RemoveOrderResponse {
   uint64 quantity_on_hold = 1 [json_name = "hold"];
 }
 
+message CancelAllOrdersRequest {}
+
+message CancelAllOrdersResponse {
+  // The order ids that are successfully removed.
+  repeated string removed_orders = 1 [json_name = "removed_orders"];
+  // The order ids that are failed to be removed.
+  repeated string failed_orders = 2 [json_name = "failed_orders"];
```
Comment (sangaman) [inline proto/xudrpc.proto:752]: I don't think this field is necessary. There shouldn't be a reason that we are unable to remove/cancel our own orders, they'll be canceled and if not there is something seriously wrong.

File: lib/orderbook/OrderBook.ts [hunk 3]
```diff
@@ -816,6 +816,23 @@ class OrderBook extends EventEmitter {
...
+        this.removeOwnOrderByLocalId(localId, true);
+        successfullyRemovedOrderIds.push(localId);
+      } catch (err) {
```
Comment (sangaman) [inline lib/orderbook/OrderBook.ts:828]: I don't think try/catch really makes sense here, since we should expect to be able to remove our own orders. The errors that could arise here would apply only if we try to remove an order that doesn't exist, but if we're removing the set of existing orders that shouldn't be an issue. We shouldn't be hitting exceptions here.

File: lib/orderbook/OrderBook.ts [hunk 4]
```diff
@@ -816,6 +816,23 @@ class OrderBook extends EventEmitter {
     return order;
   }
 
+  public removeOwnOrders = () => {
+    const successfullyRemovedOrderIds = [];
+    const failedToRemovedOrderIds = [];
+
+    for (const localId of Array.from(this.localIdMap.keys())) {
```
Comment (sangaman) [inline lib/orderbook/OrderBook.ts:823]: `Array.from` is not necessary here.

File: proto/xudrpc.proto [hunk 5]
```diff
@@ -732,6 +743,15 @@ message RemoveOrderResponse {
   uint64 quantity_on_hold = 1 [json_name = "hold"];
 }
 
+message CancelAllOrdersRequest {}
+
+message CancelAllOrdersResponse {
+  // The order ids that are successfully removed.
+  repeated string removed_orders = 1 [json_name = "removed_orders"];
```
Comment (sangaman) [inline proto/xudrpc.proto:750]: Maybe this should be `removed_order_ids`?

**Review by sangaman — CHANGES_REQUESTED** [review]
See comments.

**Comment by sangaman** [comment]
This is also definitely not a "fix" commit/PR, should be a `feat` as it's a new feature.

File: lib/cli/commands/cancelallorders.ts [hunk 6]
```diff
@@ -0,0 +1,21 @@
...
+export const describe = 'removes all orders';
+
+export const builder = (argv: Argv) => argv
+    .example('$0 cancelallorders', describe);
+
+const formatOutput = (response: CancelAllOrdersResponse.AsObject) => {
+  response.removedOrdersList.forEach((removedOrder => console.log(`Cancelled order with id ${removedOrder}`)));
+  response.failedOrdersList.forEach((failedOrder => console.log(`Failed to cancel order with id ${failedOrder}`)));
+
+  console.log('No more orders found');
```
Comment (sangaman) [inline lib/cli/commands/cancelallorders.ts:16]: One more afterthought, I don't think we need this message here, since it's a synchronous call that returns immediately. I also think we should handle the case where no orders are canceled, writing "no more orders found" when no orders were found at all doesn't make sense. Instead I think we should print "no orders found" when nothing was canceled, and just the canceled order ids without "no more orders found" when we do have orders that were canceled.

File: proto/xudrpc.proto (hunk 2 above)
Comment (rsercano) [reply proto/xudrpc.proto:752]: Alright removing then

File: lib/orderbook/OrderBook.ts (hunk 4 above)
Comment (rsercano) [reply lib/orderbook/OrderBook.ts:823]: Oh true, my bad.

**Comment by rsercano** [comment]
> This is also definitely not a "fix" commit/PR, should be a `feat` as it's a new feature.

Yeap sorry, my bad, I literally suck at commit messages.

**Comment by rsercano** [comment]
Fixed review points could you please take a look at again?

**Comment by raladev** [comment]
- [ ] it should be removeallorders,  not cancel, because our command for single order is removeorder.

**Review by raladev — CHANGES_REQUESTED** [review]
Above

**Comment by rsercano** [comment]
>  error throwing because of attempt of removing order in hold interrupts work of cancelallorders command. (Place 3 orders, start to fill one of them by peer, use cancelallorders command during swap = no removed orders)

I actually used behavior of `removeOrder` So in this case I guess it makes sense to add failed order ids into output due to on hold ? @sangaman @kilrau @raladev

**Comment by kilrau** [comment]
Yes. You can simple append the failed cancellations:
```
cancelled order with id X
cancelled order with id Y
failed to cancel order with id Z due to "on hold"
```

**Comment by sangaman** [comment]
> > error throwing because of attempt of removing order in hold interrupts work of cancelallorders command. (Place 3 orders, start to fill one of them by peer, use cancelallorders command during swap = no removed orders)
> 
> I actually used behavior of `removeOrder` except this command always tries to remove entire order quantity. So in this case I guess it makes sense to add failed order ids into output due to on hold ? @sangaman @kilrau @raladev

My apologies, this actually looks like a bug in the existing `removeOrder` logic - if it sees there's a hold on an order then it removes any quantity not on hold and then waits for holds to be resolved (if a swap fails, it'll immediately remove the quantity that's no longer on hold). However, the problem is that if there's no quantity that's not on hold, it attempts to remove 0 quantity and that throws an error. So that just needs be fixed, I'll push a fix for it separately.

With that fix the behavior would be that the call immediately goes through and removes all quantity for all orders that isn't on hold - for any holds it will wait and remove any freed up quantity automatically. Does that sound good to everyone?

**Comment by kilrau** [comment]
> for any holds it will wait and remove any freed up quantity automatically

Will the call not return until all quantity is removed? If so, assuming an order is on hold for several minutes for whatever reason, when will the removeorder call return?

**Comment by sangaman** [comment]
> > for any holds it will wait and remove any freed up quantity automatically
> 
> Will the call not return until all quantity is removed? If so, assuming an order is on hold for several minutes for whatever reason, when will the removeorder call return?

The call returns immediately after its been received, no waiting for holds to expire since those could technically take hours. With the singular remove order call it returns the quantity that's still on hold. Maybe here we could return a boolean indicating whether any orders remain on hold, or possibly a list of orders that are still on hold if we think that may be helpful.

#1921 fixes the bug I mentioned above, once that's merged we can rebase this branch on master and we shouldn't hit that "can't remove 0 quantity" error any longer.

**Comment by raladev** [comment]
https://github.com/ExchangeUnion/xud/pull/1921 is merged, @rsercano please do rebase

**Comment by raladev** [comment]
> it would be good to add info about full or partial removing to output, because order may be removed partially (because another part of order is in hold).
can be done only after https://github.com/ExchangeUnion/xud/issues/1526

So 
>error throwing because of attempt of removing order in hold interrupts work of cancelallorders command. (Place 3 orders, start to fill one of them by peer, use cancelallorders command during swap = no removed orders)
is last that we need and it should work after the rebase

**Comment by rsercano** [comment]
Rebased @raladev thanks for checking this out !

File: lib/orderbook/OrderBook.ts [hunk 7]
```diff
@@ -826,6 +826,22 @@ class OrderBook extends EventEmitter {
...
+  public removeOwnOrders = () => {
+    const removedOrderLocalIds = [];
+    const onHoldOrderLocalIds = [];
+
+    for (const localId of this.localIdMap.keys()) {
+      try {
+        this.removeOwnOrderByLocalId(localId, true);
+        removedOrderLocalIds.push(localId);
+      } catch (ex) {
+        onHoldOrderLocalIds.push(localId);
```
Comment (sangaman) [inline lib/orderbook/OrderBook.ts:838]: `removeOwnOrderByLocalId` doesn't throw an error when the order has a hold, instead it will return a non-zero number (the method comments explain in more detail). So rather than try/catching here, you should just check whether it returns 0 or not and add it to one of the two lists accordingly.

**Review by sangaman — CHANGES_REQUESTED** [review]

File: lib/orderbook/OrderBook.ts (hunk 7 above)
Comment (rsercano) [reply lib/orderbook/OrderBook.ts:838]: True that, sorry for overlooking it!

**Comment by rsercano** [comment]
Fixed @sangaman thanks for checking

**Review by erkarl — APPROVED** [review]

**Review by raladev — APPROVED** [review]

**Review by raladev — APPROVED** [review]
