### PR TITLE
fix: simplify wallet creation output

### LINKED ISSUE #1263: Simplify wallet created output
How it is:
```
The following lnd wallets were initialized: BTC, LTC
The keystore for raiden was initialized.
```

How it should be:
```
The following wallets were initialized: BTC, LTC, ERC20(ETH).
```

### PR DESCRIPTION
**Pull request by michael1011**
Closes #1263

The new output will look like this: 
```
The following wallets were initialized: LTC, BTC, ERC20(ETH)
```

### CODE REVIEW

File: lib/cli/commands/create.ts [hunk 1]
```diff
@@ -54,13 +54,22 @@ const formatOutput = (response: CreateNodeResponse.AsObject) => {
     }
     console.log('-----------------------END XUD SEED----------------------\n');
 
+    let walletInitializedMessage = 'The following wallets were initialized: ';
+
     if (response.initializedLndsList.length) {
-      console.log(`The following lnd wallets were initialized: ${response.initializedLndsList.join(', ')}`);
+      walletInitializedMessage += response.initializedLndsList.join(', ');
```
Comment (erkarl) [inline lib/cli/commands/create.ts]: What if Raiden is not initialized (only lnds)? The message will end with ", ".

Comment (michael1011) [reply lib/cli/commands/create.ts]: Not it won't because the [`join` method just puts the separator between the elements of the array](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/join). The message will end with the last entry in `response.initializedLndsList`
