### PR TITLE
fix: checking for invoice support on lnd clients while verifying connection

### LINKED ISSUE #1875: Handling LND without support for hold invoices
~~When connecting XUD with encrypted seed to a LND node outside of xud-docker which is *not* unlocked by XUD in the startup process, all swaps fail with:~~

```
08/09/2020 19:46:43.634 [LND-BTC] info: new status: WaitingUnlock
08/09/2020 19:46:43.647 [ORDERBOOK] error: swap between orders e27434d0-f20b-11ea-bded-9d25c44f1374 & 051960a0-f20c-11ea-b218-cb614d1d8fae failed due to UnexpectedClientError
08/09/2020 19:46:43.648 [ORDERBOOK] warn: swap for 200000 failed during order matching due to UnexpectedClientError, will repeat matching routine for failed quantity
08/09/2020 19:46:43.666 [LND-BTC] info: new status: Unlocked
08/09/2020 19:46:43.667 [LND-BTC] info: wallet unlocked
08/09/2020 19:46:43.701 [ORDERBOOK] error: swap between orders ddf7ad60-f20b-11ea-8eee-252d04d42534 & 051960a0-f20c-11ea-b218-cb614d1d8fae failed due to SwapClientNotSetup
08/09/2020 19:46:43.702 [ORDERBOOK] warn: swap for 200000 failed during order matching due to SwapClientNotSetup, will repeat matching routine for failed quantity
08/09/2020 19:46:43.716 [ORDERBOOK] error: swap between orders 5920a760-ed45-11ea-9ac9-6b0a18aadca8 & 051960a0-f20c-11ea-b218-cb614d1d8fae failed due to SwapClientNotSetup
08/09/2020 19:46:43.718 [ORDERBOOK] warn: swap for 100000 failed during order matching due to SwapClientNotSetup, will repeat matching routine for failed quantity
08/09/2020 19:46:47.040 [LND-BTC] info: trying to verify connection to lnd at 10.0.1.14:10009
08/09/2020 19:46:47.873 [LND-BTC] info: new status: ConnectionVerified
```

~~I can't swap on my environment because this behavior occurs every time I attempt a swap~~

I figured out the root cause of this issue: LND was not compiled with support for `invoicesrpc` (hold invoices). XUD should throw proper errors in this scenario so that the user can figure out what's wrong and sanity check the LND node (version and required RPC subsystems) on startup

### PR DESCRIPTION
**Pull request by rsercano**
Attempts to resolve #1875 

A result of getinfo where I simulated no invoice support by sending wrong rHash: @kilrau 

image

### CODE REVIEW

File: lib/lndclient/LndClient.ts [hunk 1]
```diff
@@ -72,6 +72,9 @@ class LndClient extends SwapClient {
     LTC: 2.5,
   };
 
+  // This's the hash of "This's a test invoice".
+  private static RHASH_INVOICE_CHECK = '39990D19D34FC9C27284BC7739CF5794E521CDDA3B1E0580F9DD6987FD2210DB';
```
Comment (michael1011) [inline lib/lndclient/LndClient.ts:76]: This value has to change before every attempt. Else it will fail every time after the first successful check:

image

`removeInvoice` does *not* actually remove the invoice but just cancel the XUD subscription streams and tell LND that the invoice will not be settled in the future. It is more like abandoning the invoice than removing it.

File: lib/swaps/SwapClient.ts [hunk 2]
```diff
@@ -369,6 +372,9 @@ abstract class SwapClient extends EventEmitter {
   public isOutOfSync(): boolean {
     return this.status === ClientStatus.OutOfSync;
   }
+  public isNoInvoiceSupport(): boolean {
```
Comment (michael1011) [inline lib/swaps/SwapClient.ts:375]: Let's call this method `hasNoInvoiceSupport`
```suggestion
  public hasNoInvoiceSupport(): boolean {
```

**Review by michael1011 — CHANGES_REQUESTED** [review]
Thanks for working on my obscure issue :blush:

I left some comments. And one more thing I noticed is that you call it `invoice support` which is technically not true and might be confusing for end users. I would very much prefer calling it `hold invoice support` because normal invoices are *always* supported by LND and hold invoice support is optional and has to be enabled via a flag when building LND.

**Comment by rsercano** [comment]
I fixed the review points @michael1011, will take a look at tests.

**Review by raladev — DISMISSED** [review]

File: lib/lndclient/errors.ts [hunk 3]
```diff
@@ -21,6 +22,10 @@ const errors = {
     message: `lnd-${currency} has no active channels`,
     code: errorCodes.NO_ACTIVE_CHANNELS,
   }),
+  NO_INVOICE_SUPPORT: (currency: string) => ({
+    message: `lnd-${currency} has no invoice support`,
```
Comment (erkarl) [inline lib/lndclient/errors.ts:26]:
```suggestion
    message: `lnd-${currency} has no hold invoice support`,
```

File: lib/lndclient/errors.ts [hunk 4]
```diff
@@ -21,6 +22,10 @@ const errors = {
     message: `lnd-${currency} has no active channels`,
     code: errorCodes.NO_ACTIVE_CHANNELS,
   }),
+  NO_INVOICE_SUPPORT: (currency: string) => ({
```
Comment (erkarl) [inline lib/lndclient/errors.ts:25]: Maybe rename this to `NO_HOLD_INVOICE_SUPPORT`?

**Review by raladev — APPROVED** [review]

**Review by erkarl — DISMISSED** [review]
Good job!

**Comment by erkarl** [comment]
@michael1011 good to merge from your side?

File: lib/lndclient/LndClient.ts [hunk 5]
```diff
@@ -493,6 +500,18 @@ class LndClient extends SwapClient {
         }
 
         this.invoices = new InvoicesClient(this.uri, this.credentials);
+        try {
+          const randomHash = crypto.randomBytes(32).toString('hex');
+          this.logger.info(`checking hold invoice support with hash: ${randomHash}`);
```
Comment (michael1011) [inline lib/lndclient/LndClient.ts:505]: This should be a debug message

**Review by michael1011 — COMMENTED** [review]
One minor nit but the rest looks awesome!

**Comment by rsercano** [comment]
Fixed @michael1011 thanks for checking!

**Review by michael1011 — APPROVED** [review]

**Review by erkarl — APPROVED** [review]
