### PR TITLE
 fix(swapclients): check capacity up front

### LINKED ISSUE #900: Wrong verification
From the bot log on test1:

Trying to place an order immediately after xud restart gives this error and the bot gives up on order placing.

```
2019/04/18 06:55:23 [ERROR] Lost connection to XUD. Retrying in 5 seconds
2019/04/18 06:55:28 [INFO] version:"1.0.0-alpha.11" node_pub_key:"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6" num_pairs:2 orders:<> lnd:<key:"BTC" value:<channe
ls:<active:2 pending:1 > chains:"bitcoin" blockheight:259153 version:"0.5.0-beta commit=v0.4.2-beta-1254-g13afd0b4de30c2ddb752b0095fcda3e53c01fc7e" alias:"LND for BTC on 10002/10012" >
 > lnd:<key:"LTC" value:<channels:<active:2 > chains:"litecoin" blockheight:472387 version:"0.5.0-beta commit=v0.4.2-beta-1254-g13afd0b4de30c2ddb752b0095fcda3e53c01fc7e" alias:"LND for
 LTC on 10001/10011" > > raiden:<address:"0x7ed0299Fa1ADA71D10536B866231D447cDFa48b9" > 
2019/04/18 06:55:28 [DEBUG] Placing orders
2019/04/18 06:55:28 [DEBUG] Subscribing to order events
2019/04/18 06:55:28 [DEBUG] Placing order: {0.0077 350000000 LTC/BTC  BUY} 
2019/04/18 06:55:28 [ERROR] Could not place orders: {0.0077 350000000 0} - rpc error: code = Unknown desc = LTC does not have sufficient outbound balance of: 350000000
```

However, if you restart the bot, everything works fine.

### PR DESCRIPTION
**Pull request by sangaman**
Fixes #900.

This fixes a bug where the capacity for swap clients is thought to be 0 upon initialization. The checks to update the capacity happen on an interval but not right away. This adds logic to check the capacity immediately.

This disables the `nosanitychecks` flag for the simulation tests, which will catch this bug should it regress.

I also refactored some of the logic for setting and clearing the reconnection timer since some of that code overlapped with the fix.

### CODE REVIEW

File: lib/BaseClient.ts [hunk 1]
```diff
@@ -45,28 +45,47 @@ abstract class BaseClient extends EventEmitter {
...
+
+      if (this.reconnectionTimer) {
+        clearTimeout(this.reconnectionTimer);
+        this.reconnectionTimer = undefined;
+      }
     } else {
       if (this.updateCapacityTimer) {
         clearInterval(this.updateCapacityTimer);
       }
+      if (this.status !== ClientStatus.Disabled) {
```
Comment (erkarl) [inline lib/BaseClient.ts]: I believe this change is causing a memory leak and preventing my xud from shutting down properly when using `npm run dev:watch`:

```
[1] 19/04/2019 12:35:16.611 [LND] info: LndClient status: Disconnected
[1] 19/04/2019 12:35:16.611 [LND] error: could not verify connection to lnd for BTC at localhost:10009, error: {"code":14,"metadata":{"_internal_repr":{}},"details":"Connect Failed"},
[1]           retrying in 5000 ms
[1] 19/04/2019 12:35:16.612 [LND] info: LndClient status: Disconnected
[1] 19/04/2019 12:35:21.614 [LND] info: trying to verify connection to lnd for BTC at localhost:10009
[1] 19/04/2019 12:35:21.615 [LND] info: trying to verify connection to lnd for BTC at localhost:10009
[1] 19/04/2019 12:35:27.408 [LND] error: could not verify connection to lnd for BTC at localhost:10009, error: {"code":14,"metadata":{"_internal_repr":{}},"details":"Connect Failed"},
[1]           retrying in 5000 ms
[1] 19/04/2019 12:35:27.409 [LND] info: LndClient status: Disconnected
[1] 19/04/2019 12:35:27.409 [LND] error: could not verify connection to lnd for BTC at localhost:10009, error: {"code":14,"metadata":{"_internal_repr":{}},"details":"Connect Failed"},
[1]           retrying in 5000 ms
[1] 19/04/2019 12:35:27.409 [LND] info: LndClient status: Disconnected
^C[1] 19/04/2019 12:35:28.406 [GLOBAL] info: XUD is shutting down
[1] 19/04/2019 12:35:28.408 [RPC] info: GRPC server completed shutdown
[1] 19/04/2019 12:35:28.409 [GLOBAL] info: XUD shutdown gracefully
[0] npm run compile:watch exited with code 0
--> Sending SIGTERM to other processes..
[1] 19/04/2019 12:35:32.411 [LND] info: trying to verify connection to lnd for BTC at localhost:10009
[1] 19/04/2019 12:35:39.091 [LND] error: could not verify connection to lnd for BTC at localhost:10009, error: {"code":14,"metadata":{"_internal_repr":{}},"details":"Connect Failed"},
[1]           retrying in 5000 ms
[1] 19/04/2019 12:35:39.091 [LND] info: LndClient status: Disconnected
^C[1] 19/04/2019 12:35:41.470 [GLOBAL] info: XUD is already shutting down
^C
[1] 19/04/2019 12:35:42.220 [GLOBAL] info: XUD is already shutting down
➜  xud git:(fix/capacity-checks) ✗ pgrep node | xargs kill
[1] 19/04/2019 12:35:44.096 [LND] info: trying to verify connection to lnd for BTC at localhost:10009
[1] npm run nodemon:watch exited with code 0
```

Steps to replicate:
1. start xud with lnd enabled, but stopped/disconnected
2. let it try reconnect for 2+ cycles
3. start lnd
4. close `npm run dev:watch` with ctrl+c
5. ERROR - the process is not being killed properly (I'm unable to reproduce the same behaviour in current master)

Comment (erkarl) [reply lib/BaseClient.ts]:
```
      if (this.status !== ClientStatus.Disabled) {
        /*
        if (this.reconnectionTimer) {
          console.log('debug(karl): reconnectionTimer already exists -> overwriting this.reconnectionTimer with new one');
        }
        */
        this.reconnectionTimer = setTimeout(this.verifyConnection, BaseClient.RECONNECT_TIMER);
      }
```

File: lib/orderbook/errors.ts [hunk 2]
```diff
@@ -66,8 +66,8 @@ const errors = {
     message: `unable to find swap client for currency ${currency}`,
     code: errorCodes.SWAP_CLIENT_NOT_FOUND,
   }),
-  INSUFFICIENT_OUTBOUND_BALANCE: (currency: string, amount: number) => ({
-    message: `${currency} does not have sufficient outbound balance of: ${amount}`,
+  INSUFFICIENT_OUTBOUND_BALANCE: (currency: string, amount: number, availableAmount: number) => ({
+    message: `${currency} outbound balance of ${availableAmount} is not sufficient for order amount of ${amount}`,
```
Comment (erkarl) [inline lib/orderbook/errors.ts]: Really like the more detailed error message :)

File: test/simulation/xudtest/node.go [hunk 3]
```diff
@@ -50,7 +51,6 @@ func (cfg nodeConfig) genArgs() []string {
 	var args []string
 
 	args = append(args, "--initdb=false")
-	args = append(args, "--nosanitychecks=true")
```
Comment (erkarl) [inline test/simulation/xudtest/node.go]: It's great that we get to test sanity checks and swaps now with simulation tests.

File: lib/raidenclient/RaidenClient.ts [hunk 4]
```diff
@@ -96,26 +97,21 @@ class RaidenClient extends BaseClient {
 
     this.port = port;
     this.host = host;
+    this.disable = disable;
```
Comment (erkarl) [inline lib/raidenclient/RaidenClient.ts]: Looking at the `LndClient` it might make sense to also keep port, host, disable etc. in `private config`. Probably a bit out of scope for this PR, but something to think about.

File: lib/raidenclient/RaidenClient.ts [hunk 5]
```diff
@@ -321,6 +311,7 @@ class RaidenClient extends BaseClient {
    * Returns the total balance available across all channels.
    */
   public channelBalance = async (): Promise<ChannelBalance> => {
+    // TODO: refine logic to determine balance per token rather than all combined
```
[the remark this answers is not in the document]
Comment (sangaman) [reply lib/raidenclient/RaidenClient.ts]: Yeah just thought I'd make note of it. It's OK for now but eventually we'd want to know the breakdown.

File: lib/BaseClient.ts (hunk 1 above)
Comment (sangaman) [reply lib/BaseClient.ts]: Is the issue with overwriting the timer without clearing it, you think? That would make sense to me, I just didn't realize we were setting it to disconnected twice. 

I'll go ahead and make it so we don't set a new timer if one already exists, which makes sense because it's not like we'd want to extend the timer if it's already running.

File: lib/raidenclient/RaidenClient.ts (hunk 4 above)
Comment (sangaman) [reply lib/raidenclient/RaidenClient.ts]: I was thinking about that too. I'll go ahead ane make the change.

File: lib/BaseClient.ts [hunk 6]
```diff
@@ -45,28 +45,54 @@ abstract class BaseClient extends EventEmitter {
...
     } else {
       if (this.updateCapacityTimer) {
         clearInterval(this.updateCapacityTimer);
+        this.updateCapacityTimer = undefined;
       }
+      if (this.status !== ClientStatus.Disabled) {
+        if (!this.reconnectionTimer) {
+          this.reconnectionTimer = setTimeout(this.verifyConnection, BaseClient.RECONNECT_TIMER);
+        } else {
+          this.reconnectionTimer.refresh();
```
Comment (erkarl) [inline lib/BaseClient.ts]: If we decide to use the [refresh API](https://nodejs.org/api/timers.html#timers_timeout_refresh) we'll also have to update the:
[mininum required nodejs version](https://github.com/ExchangeUnion/xud/blob/master/package.json#L182) to >=v10.2.0 and make sure we also update our simnet etc. machines. Using an older version of nodejs will crash my xud process. Otherwise the fix is working fine.

Comment (erkarl) [reply lib/BaseClient.ts]: Alternative solution (uglier, but less work) would be to just clear the timeout before setting a new one.

Comment (sangaman) [reply lib/BaseClient.ts]: You're right although I'm OK with going to node 10 as the minimum version, given that 8 is only going to be maintained through the end of the year. I'll open another PR to update the minimum version in package.json.

Comment (sangaman) [reply lib/BaseClient.ts]: I actually just went ahead and put it in this PR.
