### PR TITLE
fix: tls certificate check on startup (#1510)

### LINKED ISSUE #1510: bug: ENDENT error if user requests getinfo during initialization of xud
### Background

TS error appeared if user requests getinfo during initialization of xud.
Screen

### Steps to reproduce

1. bash xud.sh 
2. wait for container creation
3. use getinfo after xud container creation

### Expected behaviour

Readable error without error trace (see status output)

### PR DESCRIPTION
**Pull request by rsercano**
resolves #1510 

This's the only thing that I could think of to prevent startup if `tls.cert `doesn't exist. But this spits command help followed by error message.

### CODE REVIEW

**Review by raladev — CHANGES_REQUESTED** [review]
- [x] would be good to change the message to `xud is not initialized, tls.cert is not found` or to `xud is in initialization state, please wait` because `xud ` . 
`could not connect` error does not look correct because we have no connection attempt in if statement, we just checking tls path @rsercano @kilrau

**Comment by rsercano** [comment]
Changed message to `xud is in initialization state, please wait` since this looks more convenient @raladev @kilrau

**Comment by kilrau** [comment]
Can shorten `xud is in initialization state, please wait` -> `xud is initializing, please wait @rsercano

**Review by raladev — APPROVED** [review]

**Review by sangaman — CHANGES_REQUESTED** [review]
This prints `xud is initializing` even if we simply have the wrong path for the tls certificate - no matter how many times we retry the call we'd continuously get the same message unless we fix the path. That seems like undesirable behavior to me. We'd also get this message if xud isn't running and has never been run (even if the path is correct), and the error message gives the impression that we just need to wait when in reality xud needs to be manually started as it isn't actually initializing.

Perhaps instead we can wait a few seconds if we detect that the cert does not exist, try again, and if it still doesn't exist proceed with a message that we could not find the tls cert at the provided path?

@kilrau @raladev

**Comment by raladev** [comment]
> Perhaps instead we can wait a few seconds if we detect that the cert does not exist, try again, and if it still doesn't exist proceed with a message that we could not find the tls cert at the provided path?

on slow machines tls creation can take 10-15 sec, so im not sure that timer based solution is good. Maybe we can some flag that says:
0. creation flow was not initialized - print with creation/unlocking suggestion (we already have it)
1. creation flow was initialialized, but not finished - print 'xud is initializing'
2. creation flow was finished successfully/ with error - print err instead of 'xud is initializing'

**Comment by sangaman** [comment]
> > Perhaps instead we can wait a few seconds if we detect that the cert does not exist, try again, and if it still doesn't exist proceed with a message that we could not find the tls cert at the provided path?
> 
> on slow machines tls creation can take 10-15 sec, so im not sure that timer based solution is good. Maybe we can some flag that says:
> 
>     1. creation flow was not initialized - print with creation/unlocking suggestion (we already have it)
> 
>     2. creation flow was initialialized, but not finished - print 'xud is initializing'
> 
>     3. creation flow was finished successfully/ with error - print err instead of 'xud is initializing'

10-15 seconds is a lot more than what I've experienced or would have expected, is that something you've encountered?

I'm not sure how the flag you're suggesting would work, would that be a flag on the xucli command? And how would we know what's going on with the creation flow?

Since the issue appears to arise when running xud through docker, maybe we should handle that there? Docker can detect the `ENOENT` error and if it's the very first time we're running xud handle it appropriately.

**Comment by raladev** [comment]
> 10-15 seconds is a lot more than what I've experienced or would have expected, is that something you've encountered?

Yeap, usually on my VM, not on host machine.

> I'm not sure how the flag you're suggesting would work, would that be a flag on the xucli command? And how would we know what's going on with the creation flow?

for first point, yes, it can be on xucli side, but for third point it seems impossible to get result of create/initialize flow from xud if tls was not created. So it would be better to handle the case on xud-docker side like it was made in the status command.

> Since the issue appears to arise when running xud through docker, maybe we should handle that there? Docker can detect the `ENOENT` error and if it's the very first time we're running xud handle it appropriately.

make sense, we have `xud is starting` case for status command, maybe we can try to use same logic for the check on xud-docker side.

**Comment by rsercano** [comment]
So, what's the current plan for this please?

File: lib/cli/command.ts [hunk 1]
```diff
@@ -46,6 +46,9 @@ export const loadXudClient = async (argv: Arguments<any>) => {
   await loadXudConfig(argv);
 
   const certPath = argv.tlscertpath || path.join(argv.xudir, 'tls.cert');
+  if (!fs.existsSync(certPath)) {
```
Comment (sangaman) [inline lib/cli/command.ts:49]: Rather than do an `existsSync` call up front. We should wrap the `readFileSync` call and then handle the `ENOENT` error with a custom error message, otherwise rethrow the error.

File: lib/cli/command.ts [hunk 2]
```diff
@@ -56,6 +59,9 @@ export const loadXudInitClient = async (argv: Arguments<any>) => {
...
```
Comment (sangaman) [inline lib/cli/command.ts:62]: Same here, or better yet create a separate function that attempts to read and return the cert and use the function in both places, so we don't have code duplication.

**Review by sangaman — CHANGES_REQUESTED** [review]
If we don't want to make docker changes, we can print a better error message here but I think it's unusual to print a message that `xud is initializing` when we actually have no indication that that is happening.

The issue of the tls cert path being correct but a cert not being created yet while xud is running would only come up if someone starts xud for the very first time and then within seconds makes an xucli command. I think printing something like `tls cert could not be found at [path], xud may be initializing` or `tls cert could not be found at [path], it may take several seconds to be created on xud's first run` would be more correct and informative.

**Review by raladev — DISMISSED** [review]

**Review by erkarl — APPROVED** [review]

**Comment by rsercano** [comment]
There were some unnecessary whitespace changes, removed them @raladev @erkarl

**Review by raladev — APPROVED** [review]

**Review by sangaman — APPROVED** [review]
Looks very nice, thank you.

**Review by erkarl — APPROVED** [review]
