### PR TITLE
non-internal match order update

### LINKED ISSUE #276: Order matching doesn't work
I mentioned this [here](https://github.com/ExchangeUnion/xud/pull/244#issuecomment-410115395) before, matching doesn't work. First order (xud1) goes thru, second order (xud2) throws:

```
kilrau@ubuntu:~/xud/bin$ ./xucli -p 54322 placeorder BTC/LTC 1 1 99
(node:6225) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: 2 UNKNOWN: Cannot read property 'quantity' of undefined
```
```
8/3/2018, 4:43:22 PM [ORDERBOOK] debug: order match: {"maker":{"price":99,"quantity":-1,"pairId":"BTC/LTC","peerId":0,"hostId":4,"id":"ddeafc60-9776-11e8-9485-d51bda3e6ac4","invoice":"dummyInvoice","createdAt":1533339741996},"taker":{"price":99,"quantity":1,"pairId":"BTC/LTC","peerId":0,"hostId":"","id":"02234b50-9777-11e8-a286-430dcc42b522","localId":"1","createdAt":1533339802757,"invoice":""}}
8/3/2018, 4:43:22 PM [RPC] error: TypeError: Cannot read property 'quantity' of undefined
    at OrderBook.updateOrderQuantity (/home/kilrau/xud/dist/orderbook/OrderBook.js:182:62)
    at matches.forEach (/home/kilrau/xud/dist/orderbook/OrderBook.js:151:26)
    at Array.forEach (<anonymous>)
    at OrderBook.addOwnOrder (/home/kilrau/xud/dist/orderbook/OrderBook.js:149:25)
    at OrderBook.addLimitOrder (/home/kilrau/xud/dist/orderbook/OrderBook.js:94:25)
    at Service.<anonymous> (/home/kilrau/xud/dist/service/Service.js:132:53)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/service/Service.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/service/Service.js:3:12)
    at Service.placeOrder (/home/kilrau/xud/dist/service/Service.js:129:38)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:38:43)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/grpc/GrpcService.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/grpc/GrpcService.js:3:12)
    at GrpcService.unaryCall (/home/kilrau/xud/dist/grpc/GrpcService.js:36:61)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:84:18)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/grpc/GrpcService.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/grpc/GrpcService.js:3:12)

```
Nothing received on xud1. No difference if buy or sell first. Current master.

### PR DESCRIPTION
**Pull request by moshababo**
Fix #276 

* renaming existing `isOwnOrder` to `isOwnOrdersMap`
* after match, doing order update, without assuming it was an internal match
* proto `Order` message: remove `peer_id`, change `host_id` to int32 (it caused an error). 
Please regenerate the proto files for me, because I still didn't downgrade my version.

### CODE REVIEW

File: lib/orderbook/OrderBook.ts [hunk 1]
```diff
@@ -257,10 +258,14 @@ class OrderBook extends EventEmitter {
     }
   }
 
-  private isOwnOrder = (type: OrdersMap) => {
+  private isOwnOrdersMap = (type: OrdersMap) => {
     return type === this.ownOrders;
   }
 
+  private isOwnOrder = (order: orders.StampedOrder) => {
+    return !order['hostId'];
```
Comment (michael1011) [inline lib/orderbook/OrderBook.ts]: Daniel will remove the property `hostId` in #256 so we should probably use `peerId` to distinguish `peerOrder` and `ownOrder`.

File: lib/orderbook/OrderBook.ts [hunk 2]
```diff
@@ -257,10 +258,14 @@ class OrderBook extends EventEmitter {
     }
   }
 
-  private isOwnOrder = (type: OrdersMap) => {
+  private isOwnOrdersMap = (type: OrdersMap) => {
     return type === this.ownOrders;
   }
 
+  private isOwnOrder = (order: orders.StampedOrder) => {
```
Comment (sangaman) [inline lib/orderbook/OrderBook.ts]: I think this doesn't need to be an instance method - it can just be moved out of the class - and made a regular method, and you can tell the compiler that this checks for `StampedOwnOrder` types. I also think it would be nice to check for `localId` as well and for the right types:

```javascript
function isOwnOrder(order: orders.StampedOrder): order is StampedOwnOrder {
  return order['hostId'] === undefined && typeof order['localId'] === 'string';
}
```

File: lib/orderbook/OrderBook.ts (hunk 1 above)
Comment (sangaman) [reply lib/orderbook/OrderBook.ts]: True, although I guess it should be handled in whichever gets merged second.

**Comment by kilrau** [comment]
Testing results:
xud1:
```kilrau@ubuntu:~/xud/bin$ ./xucli -p 1235 placeorder BTC/LTC 2 -1 99
(node:10123) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
{
  "matchesList": [],
  "remainingOrder": {
    "price": 99,
    "quantity": -1,
    "pairId": "BTC/LTC",
    "peerId": 0,
    "hostId": "",
    "id": "dd5208b0-98df-11e8-8bfe-178a646fed42",
    "localId": "2",
    "createdAt": 1533494789307,
    "invoice": ""
  }
```

xud2 (summary always fails with `Error: 13 INTERNAL: Failed to parse server response`, then succeeds to place order. Match logs still don't show 'match', just 'dummy invoice')
```
kilrau@ubuntu:~/xud/bin$ ./xucli -p 54322 placeorder BTC/LTC 2 1 99
(node:10136) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: 13 INTERNAL: Failed to parse server response
kilrau@ubuntu:~/xud/bin$ ./xucli -p 54322 placeorder BTC/LTC 2 1 99
(node:10149) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
{
  "matchesList": [],
  "remainingOrder": {
    "price": 99,
    "quantity": 1,
    "pairId": "BTC/LTC",
    "peerId": 0,
    "hostId": "",
    "id": "e12de350-98df-11e8-a999-8d26d92e5cfc",
    "localId": "2",
    "createdAt": 1533494795781,
    "invoice": ""
  }
}
```
```
8/5/2018, 11:46:29 AM [P2P] debug: Received data (127.0.0.1:42564): {"header":{"id":"dd527de0-98df-11e8-8bfe-178a646fed42","hash":"OJKSOvg+ti5IsdsRrUQqqQ==","type":"ORDER"},"body":{"price":99,"quantity":-1,"pairId":"BTC/LTC","hostId":0,"id":"dd5208b0-98df-11e8-8bfe-178a646fed42","invoice":"dummyInvoice"}}

8/5/2018, 11:46:29 AM [ORDERBOOK] debug: order added: {"price":99,"quantity":-1,"pairId":"BTC/LTC","hostId":37,"id":"dd5208b0-98df-11e8-8bfe-178a646fed42","invoice":"dummyInvoice","createdAt":1533494789312}
8/5/2018, 11:46:29 AM [P2P] debug: Received data (localhost:1234): {"header":{"id":"dd527de0-98df-11e8-8bfe-178a646fed42","hash":"OJKSOvg+ti5IsdsRrUQqqQ==","type":"ORDER"},"body":{"price":99,"quantity":-1,"pairId":"BTC/LTC","hostId":0,"id":"dd5208b0-98df-11e8-8bfe-178a646fed42","invoice":"dummyInvoice"}}

8/5/2018, 11:46:29 AM [ORDERBOOK] debug: order added: {"price":99,"quantity":-1,"pairId":"BTC/LTC","hostId":27,"id":"dd5208b0-98df-11e8-8bfe-178a646fed42","invoice":"dummyInvoice","createdAt":1533494789313}
8/5/2018, 11:46:34 AM [ORDERBOOK] debug: order match: {"maker":{"price":99,"quantity":-1,"pairId":"BTC/LTC","hostId":37,"id":"dd5208b0-98df-11e8-8bfe-178a646fed42","invoice":"dummyInvoice","createdAt":1533494789312},"taker":{"price":99,"quantity":1,"pairId":"BTC/LTC","hostId":0,"id":"e035eec0-98df-11e8-a999-8d26d92e5cfc","localId":"2","createdAt":1533494794156,"invoice":""}}
8/5/2018, 11:46:35 AM [ORDERBOOK] debug: order added: {"price":99,"quantity":1,"pairId":"BTC/LTC","hostId":0,"id":"e12de350-98df-11e8-a999-8d26d92e5cfc","localId":"2","createdAt":1533494795781,"invoice":""}
8/5/2018, 11:46:35 AM [P2P] debug: Received data (127.0.0.1:42498): {"header":{"id":"e12e3170-98df-11e8-a999-8d26d92e5cfc","hash":"UgFNWYPOE9WPtgTqXSNM+g==","type":"ORDER"},"body":{"price":99,"quantity":1,"pairId":"BTC/LTC","hostId":0,"id":"e12de350-98df-11e8-a999-8d26d92e5cfc","invoice":"dummyInvoice"}}

8/5/2018, 11:46:35 AM [ORDERBOOK] debug: order added: {"price":99,"quantity":1,"pairId":"BTC/LTC","hostId":36,"id":"e12de350-98df-11e8-a999-8d26d92e5cfc","invoice":"dummyInvoice","createdAt":1533494795784}
8/5/2018, 11:46:35 AM [P2P] debug: Received data (localhost:54321): {"header":{"id":"e12e3170-98df-11e8-a999-8d26d92e5cfc","hash":"UgFNWYPOE9WPtgTqXSNM+g==","type":"ORDER"},"body":{"price":99,"quantity":1,"pairId":"BTC/LTC","hostId":0,"id":"e12de350-98df-11e8-a999-8d26d92e5cfc","invoice":"dummyInvoice"}}

8/5/2018, 11:46:35 AM [ORDERBOOK] debug: order added: {"price":99,"quantity":1,"pairId":"BTC/LTC","hostId":28,"id":"e12de350-98df-11e8-a999-8d26d92e5cfc","invoice":"dummyInvoice","createdAt":1533494795784}
8/5/2018, 11:46:49 AM [P2P] debug: Received data (127.0.0.1:42498): {"header":{"id":"e93c9230-98df-11e8-a999-8d26d92e5cfc","type":"PING"}}

```

**Comment by moshababo** [comment]
@kilrau did you trying to running it after @michael1011 commit?

**Comment by kilrau** [comment]
Tested again - works with @michael1011 s protobufs

File: lib/orderbook/OrderBook.ts (hunk 2 above)
Comment (moshababo) [reply lib/orderbook/OrderBook.ts]: Right, I made it static instead because I'm usually not in favor of making function hanging in the file, specially if they do relate to the class.

I added the `localId` check, we'll need to keep an eye on it in case it will become optional.

**Comment by sangaman** [comment]
Oops, posted this in the wrong PR discussion by mistake: Per @michael1011 's comment, I think it would be nice to have #256 merged before this so we don't need to make changes just to immediately throw them out after #256, so if you have a chance to review that soonish @moshababo that would be great.

File: lib/orderbook/OrderBook.ts (hunk 2 above)
Comment (sangaman) [reply lib/orderbook/OrderBook.ts]: Did you commit those changes yet? I don't see them.

I think if you want to keep it as part of the class and make it static and add the `order is orders.StampedOwnOrder` to it that'd be fine. It actually might make more sense to move this function to the orders.ts file where `orders.StampedOwnOrder` is defined.

Comment (moshababo) [reply lib/orderbook/OrderBook.ts]: Just noticed that the push failed :\

**Comment by moshababo** [comment]
#256 is merged to master, and this branch is updated. 

I made a change in the proto file again (`peerId` was int32 instead of string), so the protos need to be reregenerated. (i'll be downgrading soon, just been having an issue with it and I didn't want to delay on that)

**Comment by michael1011** [comment]
We will need to come up with a better solution to generate the protobufs eventually. It works fine on my laptop but on my main machine there many unnecessary changes although they are on the exact same versions.
